<?php

// Script to add CSS lessons 21-40 to the Ferga section in Firebase
$firebaseUrl = 'https://ai-platform-adb1b-default-rtdb.firebaseio.com/';
$idToken = trim(file_get_contents('/tmp/opencode/fb_token.txt'));
$langId = '-OyrwFaGbQ7K-1QnzHvq';

function fbPost($url, $data) {
    global $idToken;
    $ch = curl_init($url . '?auth=' . urlencode($idToken));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
    $res = curl_exec($ch);
    curl_close($ch);
    return $res;
}

function lesson($order, $level_so, $level_ba, $title_so, $title_ba, $content_so, $content_ba, $code) {
    return [
        'order' => $order,
        'level_so' => $level_so,
        'level_ba' => $level_ba,
        'title_so' => $title_so,
        'title_ba' => $title_ba,
        'content_so' => $content_so,
        'content_ba' => $content_ba,
        'code' => $code,
        'example_output' => '',
        'challenge_desc_so' => '',
        'challenge_desc_ba' => '',
        'expected_output' => '',
    ];
}

$lv3so = 'ئاستی ٣ - پێشکەوتوو';
$lv3ba = 'ئاستا ٣ - پێشکەفتی';
$lv4so = 'ئاستی ٤ - پرۆژەکان';
$lv4ba = 'ئاستا ٤ - پروژە';

$lessons = [
    lesson(21, $lv3so, $lv3ba, 'فۆنتە ئۆنلاینەکان (Google Fonts)', 'فۆنتێن ئۆنلاین (Google Fonts)',
        '<p>بۆ فۆنتی زیاتر، لە Google Fonts:</p><pre>&lt;link href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic&amp;display=swap" rel="stylesheet"&gt;</pre><p>پاشان لە CSS:</p><pre>body { font-family: "Noto Naskh Arabic", sans-serif; }</pre><p>بۆ فۆنتەکانی کوردی، Noto Naskh Arabic و Vazirmatn بژاردەی باشن. بۆ خێرایی پەڕەکە، تەنها ئەو ستایلی فۆنتە هەڵبژێرە کە پێویستتە.</p>',
        '<p>بو فۆنتێن بەرتر، ژ Google Fonts:</p><pre>&lt;link href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic&amp;display=swap" rel="stylesheet"&gt;</pre><p>پاشی د CSS دا:</p><pre>body { font-family: "Noto Naskh Arabic", sans-serif; }</pre><p>بو فۆنتێن کوردی، Noto Naskh Arabic و Vazirmatn هەلبژارتنێن باشن. بو خێراییا رووپەلێ، تەنها وی ستایلێ فۆنتی هەلبژیرە کو پێدڤییە.</p>',
        "@import url('https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;700&family=Poppins:wght@400;700&display=swap');\n\nbody {\n    font-family: \"Noto Naskh Arabic\", sans-serif;\n}\n\nh1, h2 {\n    font-family: \"Poppins\", sans-serif;\n    font-weight: 700;\n}\n\np {\n    font-weight: 400;\n}"),

    lesson(22, $lv3so, $lv3ba, 'ڤاریەیبڵەکانی CSS', 'گۆڕۆکێن CSS',
        '<p><bdi>custom properties</bdi> (ڤاریەیبڵ) بە <bdi>--</bdi> دەست پێ دەکەن:</p><pre>:root {\n  --primary: #1565c0;\n  --spacing: 16px;\n}\n\n.btn {\n  background: var(--primary);\n  padding: var(--spacing);\n}</pre><p>بە <bdi>var()</bdi> بەهایان بەکاربهێنە. گۆڕینی یەک بەها لە :root دا، هەموو پەڕەکە دەگۆڕێت. بۆ تەوەمی تاریک و ڕووناک زۆر باشە.</p>',
        '<p><bdi>custom properties</bdi> (گۆڕۆک) پێ <bdi>--</bdi> دست پێ دکەن:</p><pre>:root {\n  --primary: #1565c0;\n  --spacing: 16px;\n}\n\n.btn {\n  background: var(--primary);\n  padding: var(--spacing);\n}</pre><p>پێ <bdi>var()</bdi> بەها بکاربینی. گوهۆرینا یەک بەهایێ د :root دا، هەمی رووپەل دگوهۆریت. بو تەوەمێ تاریک و ڕووناک زۆر باشە.</p>',
        ":root {\n    --primary: #1565c0;\n    --primary-dark: #0d47a1;\n    --success: #2e7d32;\n    --danger: #c62828;\n    --radius: 8px;\n    --spacing: 16px;\n    --shadow: 0 2px 8px rgba(0, 0, 0, 0.15);\n}\n\nbody {\n    font-family: Arial, sans-serif;\n    margin: var(--spacing);\n}\n\n.btn {\n    padding: 10px 20px;\n    border: none;\n    border-radius: var(--radius);\n    box-shadow: var(--shadow);\n}\n\n.btn-success {\n    background: var(--success);\n    color: white;\n}\n\n.btn-danger {\n    background: var(--danger);\n    color: white;\n}"),

    lesson(23, $lv3so, $lv3ba, 'مێدیا کوێری (Responsive)', 'مێدیا کوێری',
        '<p><bdi>@media</bdi> بەپێی قەبارەی پەنجەرەکە ستایل جیاواز دیاری دەکات:</p><pre>/* Mobayl: bi seretayî */\n.menu { display: none; }\n\n/* Tablet û mezintir */\n@media (min-width: 768px) {\n  .menu { display: flex; }\n}\n\n@media (max-width: 600px) {\n  h1 { font-size: 20px; }\n}</pre><p>بنەڕەتی موبایل بێت (mobile-first) و پاشان بە min-width بەشەکانی تر. بە <bdi>meta viewport</bdi> لە HTML.</p>',
        '<p><bdi>@media</bdi> ل گورەیا قەبارا پەنجەرێ ستایلێن جودا دیاری دکەت:</p><pre>/* Mobayl: ب بنگەهی */\n.menu { display: none; }\n\n/* Tablet و مەزنتر */\n@media (min-width: 768px) {\n  .menu { display: flex; }\n}\n\n@media (max-width: 600px) {\n  h1 { font-size: 20px; }\n}</pre><p>بنگەهێ mobayl بیت (mobile-first) و پاشی پێ min-width بەشێن دی. ل گەل <bdi>meta viewport</bdi> د HTML دا.</p>',
        "* { box-sizing: border-box; }\n\nbody {\n    font-family: Arial;\n    margin: 0;\n}\n\n.layout {\n    display: grid;\n    grid-template-columns: 1fr;\n}\n\n.sidebar {\n    display: none;\n    background: #263238;\n    color: white;\n    padding: 15px;\n}\n\n@media (min-width: 768px) {\n    .layout {\n        grid-template-columns: 250px 1fr;\n    }\n    .sidebar {\n        display: block;\n    }\n}\n\n@media (max-width: 500px) {\n    h1 {\n        font-size: 22px;\n    }\n}"),

    lesson(24, $lv3so, $lv3ba, 'فلێکس و گرید پێکەوە', 'فلێکس و گرید پێکەوە',
        '<p>فلێکس بۆ ڕیزەک و گرید بۆ پەڕە. نموونە: گرید بۆ لایۆتی گشتی و فلێکس بۆ ناو هەر بەشێک:</p><pre>.page {\n  display: grid;\n  grid-template-columns: 1fr 3fr;\n}\n\n.header {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}</pre><p>هەروەها فلێکس و گرید دەتوانن لە ناو یەکتردا بن. باشترین پراکتیک: گرید بۆ لایۆت، فلێکس بۆ ڕیزکردنی ناوەڕۆک.</p>',
        '<p>فلێکس بو ڕیزەک و گرید بو پەڕە. نمونە: گرید بو لایۆتا گشتی و فلێکس بو د ناڤ هەر بەشەکێ:</p><pre>.page {\n  display: grid;\n  grid-template-columns: 1fr 3fr;\n}\n\n.header {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}</pre><p>هەروەسا فلێکس و گرید دکەن د ناڤ هەڤدا بن. پراکتیکا باشترین: گرید بو لایۆت، فلێکس بو ڕیزکرنا ناڤەرۆکی.</p>',
        ".page {\n    display: grid;\n    grid-template-columns: 1fr 3fr;\n    gap: 20px;\n    max-width: 1000px;\n    margin: auto;\n}\n\n.sidebar {\n    background: #eceff1;\n    padding: 15px;\n}\n\n.sidebar ul {\n    list-style: none;\n    padding: 0;\n}\n\n.sidebar li {\n    padding: 8px;\n    margin: 4px 0;\n    background: white;\n    border-radius: 4px;\n}\n\n.content {\n    display: flex;\n    flex-direction: column;\n    gap: 15px;\n}\n\n.post {\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n    background: white;\n    border: 1px solid #ddd;\n    padding: 12px;\n}"),

    lesson(25, $lv3so, $lv3ba, 'فوورم ستایلینگ', 'ستایلکرنا فۆرمێ',
        '<p>فۆڕمێکی جوان بە CSS:</p><pre>input, textarea, select {\n  width: 100%;\n  padding: 12px;\n  border: 1px solid #ccc;\n  border-radius: 6px;\n  font-size: 16px;\n}\n\ninput:focus {\n  border-color: #1976d2;\n  box-shadow: 0 0 0 3px rgba(25,118,210,0.2);\n  outline: none;\n}</pre><p>بە <bdi>placeholder</bdi> ڕەنگی نیشانەکان دیاری بکە و بە <bdi>:invalid</bdi> دۆخی هەڵە نیشان بدە.</p>',
        '<p>فۆرمەکا جوان پێ CSS:</p><pre>input, textarea, select {\n  width: 100%;\n  padding: 12px;\n  border: 1px solid #ccc;\n  border-radius: 6px;\n  font-size: 16px;\n}\n\ninput:focus {\n  border-color: #1976d2;\n  box-shadow: 0 0 0 3px rgba(25,118,210,0.2);\n  outline: none;\n}</pre><p>پێ <bdi>placeholder</bdi> ڕەنگا نیشانان دیاری کە و پێ <bdi>:invalid</bdi> دۆخا خەلەتی نیشان بدە.</p>',
        ".form {\n    max-width: 400px;\n    margin: auto;\n    padding: 20px;\n    background: white;\n    border-radius: 10px;\n    box-shadow: 0 2px 10px rgba(0,0,0,0.1);\n}\n\nlabel {\n    display: block;\n    margin: 12px 0 4px;\n    font-weight: bold;\n}\n\ninput, textarea, select {\n    width: 100%;\n    padding: 10px;\n    border: 1px solid #ccc;\n    border-radius: 6px;\n    box-sizing: border-box;\n}\n\ninput:focus {\n    border-color: #1976d2;\n    box-shadow: 0 0 0 3px rgba(25, 118, 210, 0.2);\n    outline: none;\n}\n\ninput:invalid {\n    border-color: #c62828;\n}\n\nbutton {\n    background: #1976d2;\n    color: white;\n    border: none;\n    padding: 12px;\n    width: 100%;\n    margin-top: 15px;\n    border-radius: 6px;\n}"),

    lesson(26, $lv3so, $lv3ba, 'ناڤیگەیشن بار', 'بارا ناڤیگەیشنێ',
        '<p>ناڤیگەیشنی جوان بە فلێکس:</p><pre>.navbar {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  background: #263238;\n  padding: 0 20px;\n}\n\n.navbar a {\n  color: white;\n  text-decoration: none;\n  padding: 15px;\n}\n\n.navbar a:hover {\n  background: #37474f;\n}</pre><p>بۆ ئەو لینکەی ئەمڕۆ لەسەرە: <bdi>.active</bdi> بە ڕەنگی جیاواز. بۆ موبایل، لینکەکان لە خوارەوە ڕیز بکە.</p>',
        '<p>ناڤیگەیشنەکا جوان پێ فلێکس:</p><pre>.navbar {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  background: #263238;\n  padding: 0 20px;\n}\n\n.navbar a {\n  color: white;\n  text-decoration: none;\n  padding: 15px;\n}\n\n.navbar a:hover {\n  background: #37474f;\n}</pre><p>بو ڤێ گرێدانا ئەڤرۆ: <bdi>.active</bdi> ب ڕەنگەکا جودا. بو mobayl، گرێدان د خوارێ دا ڕیز کە.</p>',
        ".navbar {\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n    background: #263238;\n    padding: 0 20px;\n    font-family: Arial;\n}\n\n.navbar .logo {\n    color: #ffd54f;\n    font-size: 22px;\n    font-weight: bold;\n}\n\n.navbar ul {\n    display: flex;\n    list-style: none;\n    margin: 0;\n    padding: 0;\n}\n\n.navbar a {\n    display: block;\n    color: white;\n    text-decoration: none;\n    padding: 16px 18px;\n    transition: background 0.2s;\n}\n\n.navbar a:hover,\n.navbar a.active {\n    background: #e91e63;\n}\n\n@media (max-width: 600px) {\n    .navbar {\n        flex-direction: column;\n        align-items: stretch;\n    }\n    .navbar ul {\n        flex-direction: column;\n    }\n}"),

    lesson(27, $lv3so, $lv3ba, 'ڕووکاری تاریک (Dark Mode)', 'ڕووکاری تاریک (Dark Mode)',
        '<p>تەوەمی تاریک بە ڤاریەیبڵ و media query:</p><pre>:root {\n  --bg: #ffffff;\n  --text: #212121;\n}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n    --bg: #121212;\n    --text: #e0e0e0;\n  }\n}\n\nbody {\n  background: var(--bg);\n  color: var(--text);\n}</pre><p><bdi>prefers-color-scheme</bdi> بەپێی وەرگری بەکارهێنەر (dark/light) خۆکارانە دەگۆڕێت. هەروەها دەتوانیت بە کلاسی <bdi>.dark</bdi> و JavaScript کۆنترۆڵ بکەیت.</p>',
        '<p>تەوەمێ تاریک پێ گۆڕۆک و media query:</p><pre>:root {\n  --bg: #ffffff;\n  --text: #212121;\n}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n    --bg: #121212;\n    --text: #e0e0e0;\n  }\n}\n\nbody {\n  background: var(--bg);\n  color: var(--text);\n}</pre><p><bdi>prefers-color-scheme</bdi> ل گورەیا وەرگرا بکارهێنەری (dark/light) ب شێوەیەکا خودکار دگوهوری. هەروەسا دکەی پێ کلاسا <bdi>.dark</bdi> و JavaScript کۆنترۆل کەی.</p>',
        ":root {\n    --bg: #ffffff;\n    --text: #212121;\n    --card: #f5f5f5;\n    --primary: #1565c0;\n}\n\n@media (prefers-color-scheme: dark) {\n    :root {\n        --bg: #121212;\n        --text: #e0e0e0;\n        --card: #1e1e1e;\n        --primary: #64b5f6;\n    }\n}\n\nbody {\n    background: var(--bg);\n    color: var(--text);\n    font-family: Arial;\n    margin: 0;\n}\n\n.card {\n    background: var(--card);\n    padding: 20px;\n    border-radius: 8px;\n    margin: 20px;\n}\n\n.btn {\n    background: var(--primary);\n    color: white;\n    border: none;\n    padding: 10px 20px;\n    border-radius: 6px;\n}"),

    lesson(28, $lv4so, $lv4ba, 'پرۆژە: کارتی سادە', 'پروژە: کارتەکا ساده',
        '<p>یەکەم پرۆژەی CSS: کارتی سادە. تێیدا:</p><ul><li>سێبەر و گۆشەی گراند</li><li>ترانزیشن لەسەر hover</li><li>بۆردەر و ڕەنگی باش</li></ul><p>کارت لە زۆرترین شوێن بەکاردێت: بەرهەم، پۆست، هەواڵ. کارتی پاکیزە و جوان دروست بکە.</p>',
        '<p>پروژەیا یەکێ د CSS دا: کارتەکا ساده. د ناڤ دا:</p><ul><li>سێبەر و گۆشەیێن گراندی</li><li>ترانزیشن ل سەر hover</li><li>بۆردەر و ڕەنگەکا باش</li></ul><p>کارت د زۆربەی جهیان دا بکارتیت: بەرهەم، پۆست، نڤیسار. کارتەکا پاقژ و جوان دروست کە.</p>',
        ".card {\n    width: 280px;\n    margin: 20px auto;\n    background: white;\n    border-radius: 12px;\n    overflow: hidden;\n    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.12);\n    transition: transform 0.3s, box-shadow 0.3s;\n}\n\n.card:hover {\n    transform: translateY(-5px);\n    box-shadow: 0 12px 25px rgba(0, 0, 0, 0.2);\n}\n\n.card img {\n    width: 100%;\n    height: 160px;\n    object-fit: cover;\n}\n\n.card-body {\n    padding: 15px 20px;\n}\n\n.card-body h3 {\n    margin: 0 0 8px;\n    font-size: 18px;\n}\n\n.card-body p {\n    color: #666;\n    font-size: 14px;\n    line-height: 1.5;\n}\n\n.card .btn {\n    display: inline-block;\n    margin: 10px 20px 20px;\n    padding: 8px 20px;\n    background: #1976d2;\n    color: white;\n    border-radius: 20px;\n    text-decoration: none;\n    font-size: 14px;\n}"),

    lesson(29, $lv4so, $lv4ba, 'پرۆژە: دوگمەکان', 'پروژە: دوگمەیان',
        '<p>پرۆژە: کۆمەڵە دوگمەی جوان:</p><ul><li>دوگمەی سەرەکی (primary)</li><li>دوگمەی لاوەکی (secondary)</li><li>دوگمەی مەترسی (danger)</li><li>دوگمەی وێنەیی (icon)</li></ul><p>دوگمە بۆ هەموو کردارەکان: ناردن، داخستن، سڕینەوە. قەبارەی <bdi>padding</bdi> و <bdi>border-radius</bdi> و <bdi>cursor: pointer</bdi> بیر نەکەن.</p>',
        '<p>پروژە: کۆمەلەک دوگمەیێن جوان:</p><ul><li>دوگمەیا سەرەکی (primary)</li><li>دوگمەیا لاوەکی (secondary)</li><li>دوگمەیا مه‌ترسی (danger)</li><li>دوگمەیا وێنەیی (icon)</li></ul><p>دوگمە بو هەمی کرداران: شاندن، داخستن، ژێبرن. قەبارا <bdi>padding</bdi> و <bdi>border-radius</bdi> و <bdi>cursor: pointer</bdi> بەرچاڤ نەکەڤن.</p>',
        ".btn {\n    display: inline-block;\n    padding: 12px 28px;\n    border: none;\n    border-radius: 6px;\n    font-size: 15px;\n    cursor: pointer;\n    transition: all 0.25s ease;\n    text-decoration: none;\n}\n\n.btn-primary {\n    background: #1976d2;\n    color: white;\n}\n\n.btn-primary:hover {\n    background: #0d47a1;\n    box-shadow: 0 4px 12px rgba(25, 118, 210, 0.4);\n}\n\n.btn-outline {\n    background: transparent;\n    color: #1976d2;\n    border: 2px solid #1976d2;\n}\n\n.btn-outline:hover {\n    background: #e3f2fd;\n}\n\n.btn-danger {\n    background: #c62828;\n    color: white;\n}\n\n.btn-danger:hover {\n    background: #b71c1c;\n}\n\n.btn-ghost {\n    background: transparent;\n    color: #333;\n}\n\n.btn-ghost:hover {\n    background: #f0f0f0;\n}"),

    lesson(30, $lv4so, $lv4ba, 'پرۆژە: کارتی پڕۆفایل', 'پروژە: کارتا پڕۆفایلێ',
        '<p>پرۆژە: کارتی پڕۆفایل بۆ تۆڕە کۆمەڵایەتییەکان:</p><ul><li>وێنەی پڕۆفایل بە بازنە</li><li>ناو و پیشە</li><li>ستاتیک: فۆڵۆوەر، پۆست</li><li>دوگمەی بەدواداچوون</li></ul><p>فلێکس بۆ ڕیزکردنی بەشەکان و شادۆ بۆ قووڵایی.</p>',
        '<p>پروژە: کارتا پڕۆفایلێ بو تۆڕێن کۆمەلایەتی:</p><ul><li>وێنەیا پڕۆفایلێ ب بازنە</li><li>ناڤ و پیشە</li><li>ستاتیک: فۆڵۆوەر، پۆست</li><li>دوگمەیا بەدواخوازی</li></ul><p>فلێکس بو ڕیزکرنا بەشان و شادۆ بو قولاییێ.</p>',
        ".profile-card {\n    width: 300px;\n    margin: 30px auto;\n    background: white;\n    border-radius: 16px;\n    overflow: hidden;\n    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.15);\n    text-align: center;\n}\n\n.cover {\n    height: 90px;\n    background: linear-gradient(120deg, #1565c0, #64b5f6);\n}\n\n.avatar {\n    width: 90px;\n    height: 90px;\n    border-radius: 50%;\n    border: 4px solid white;\n    margin-top: -45px;\n    object-fit: cover;\n}\n\n.profile-card h3 {\n    margin: 8px 0 2px;\n}\n\n.profile-card .job {\n    color: #999;\n    font-size: 14px;\n    margin: 0;\n}\n\n.stats {\n    display: flex;\n    justify-content: space-around;\n    border-top: 1px solid #eee;\n    margin-top: 15px;\n    padding: 12px 0;\n}\n\n.stats b {\n    font-size: 18px;\n}\n\n.stats span {\n    font-size: 12px;\n    color: #777;\n}\n\n.follow {\n    margin: 15px 0;\n    padding: 10px 30px;\n    background: #1976d2;\n    color: white;\n    border: none;\n    border-radius: 25px;\n    cursor: pointer;\n}"),

    lesson(31, $lv4so, $lv4ba, 'پرۆژە: فۆڕمی جوان', 'پروژە: فۆرمەکا جوان',
        '<p>پرۆژە: فۆڕمی تۆمارکردنی جوان:</p><ul><li>ناونیشان و وەسف</li><li>خانەکان بە ستایلی باش</li><li>دۆخی focus</li><li>دوگمەی ناردن بە پڕ</li></ul><p>فۆڕمی باش بۆ ناردنی داتا لە هەموو پەڕەیەک. ستایلی <bdi>:focus</bdi> و <bdi>placeholder</bdi> نەلێرن.</p>',
        '<p>پروژە: فۆرمەکا تۆمارکرنا جوان:</p><ul><li>ناڤ و وەسف</li><li>خانە پێ ستایلەکا باش</li><li>دۆخا focus</li><li>دوگمەیا شاندنێ تیژ</li></ul><p>فۆرمەکا باش بو شاندنا داتایێ د هەمی رووپەلان دا. ستایلێ <bdi>:focus</bdi> و <bdi>placeholder</bdi> نەلێرە.</p>',
        ".register-form {\n    max-width: 380px;\n    margin: 40px auto;\n    background: white;\n    padding: 30px;\n    border-radius: 12px;\n    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.12);\n}\n\n.register-form h2 {\n    margin: 0 0 5px;\n    text-align: center;\n}\n\n.register-form .sub {\n    text-align: center;\n    color: #777;\n    margin: 0 0 20px;\n}\n\n.field {\n    margin-bottom: 14px;\n}\n\n.field label {\n    display: block;\n    font-size: 13px;\n    font-weight: bold;\n    margin-bottom: 5px;\n}\n\n.field input {\n    width: 100%;\n    padding: 10px 12px;\n    border: 1px solid #ccc;\n    border-radius: 6px;\n    box-sizing: border-box;\n    transition: border-color 0.2s, box-shadow 0.2s;\n}\n\n.field input:focus {\n    border-color: #1976d2;\n    box-shadow: 0 0 0 3px rgba(25, 118, 210, 0.15);\n    outline: none;\n}\n\n.submit-btn {\n    width: 100%;\n    padding: 12px;\n    background: linear-gradient(90deg, #1976d2, #42a5f5);\n    color: white;\n    border: none;\n    border-radius: 6px;\n    font-size: 15px;\n    cursor: pointer;\n}"),

    lesson(32, $lv4so, $lv4ba, 'پرۆژە: گالەری ڕیسپۆنسیڤ', 'پروژە: گالەریا ڕیسپۆنسیڤ',
        '<p>پرۆژە: گالەری ڕیسپۆنسیڤ بە گرید:</p><pre>.gallery {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n  gap: 12px;\n}\n\n.gallery img {\n  width: 100%;\n  height: 200px;\n  object-fit: cover;\n}</pre><p>بە <bdi>auto-fit</bdi> و <bdi>minmax</bdi> گالەری خۆکارانە لەگەڵ قەبارەی پەنجەرەکە دەگونجێت بێ هیچ media query یەک.</p>',
        '<p>پروژە: گالەریا ڕیسپۆنسیڤ پێ گرید:</p><pre>.gallery {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n  gap: 12px;\n}\n\n.gallery img {\n  width: 100%;\n  height: 200px;\n  object-fit: cover;\n}</pre><p>پێ <bdi>auto-fit</bdi> و <bdi>minmax</bdi> گالەری ب شێوەیەکا خودکار پێ قەبارا پەنجەرێ دگونجیت بێ هیچ media query یەک.</p>',
        ".gallery {\n    display: grid;\n    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n    gap: 12px;\n    max-width: 1000px;\n    margin: 20px auto;\n}\n\n.gallery img {\n    width: 100%;\n    height: 200px;\n    object-fit: cover;\n    border-radius: 8px;\n    transition: transform 0.3s;\n}\n\n.gallery img:hover {\n    transform: scale(1.03);\n}"),

    lesson(33, $lv4so, $lv4ba, 'پرۆژە: لاندینگ پەیج', 'پروژە: لاندینگ پەیج',
        '<p>پرۆژە: لاندینگ پەیج بە CSS:</p><ul><li>بەشی پێشوازی (hero) بە گرادینت</li><li>کارتی تایبەتمەندییەکان (گرید)</li><li>دوگمەی CTA</li><li>ڕیسپۆنسیڤ</li></ul><p>لاندینگ پەیج دەبێت سادە بێت: ناونیشانێکی ڕوون، وەسف، و دوگمەیەک. فۆنتی گەورە و بۆشایی باش بەکاربهێنە.</p>',
        '<p>پروژە: لاندینگ پەیج پێ CSS:</p><ul><li>بەشا پێشوازیێ (hero) پێ گرادینت</li><li>کارتێن تایبەتمەندییان (گرید)</li><li>دوگمەیا CTA</li><li>ڕیسپۆنسیڤ</li></ul><p>لاندینگ پەیج دڤێت ساده بیت: ناڤەکەکا ڕوون، وەسف، و دوگمەکا. فۆنتا مەزن و بۆشاییا باش بکاربینی.</p>',
        "* { box-sizing: border-box; }\n\nbody {\n    margin: 0;\n    font-family: Arial, sans-serif;\n}\n\n.hero {\n    background: linear-gradient(135deg, #6a1b9a, #ab47bc);\n    color: white;\n    text-align: center;\n    padding: 90px 20px;\n}\n\n.hero h1 {\n    font-size: 48px;\n    margin: 0 0 10px;\n}\n\n.hero p {\n    font-size: 18px;\n    opacity: 0.9;\n    margin: 0 0 30px;\n}\n\n.cta {\n    background: white;\n    color: #6a1b9a;\n    border: none;\n    padding: 14px 40px;\n    border-radius: 30px;\n    font-size: 16px;\n    cursor: pointer;\n    transition: transform 0.2s;\n}\n\n.cta:hover {\n    transform: scale(1.05);\n}\n\n.features {\n    display: grid;\n    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));\n    gap: 20px;\n    max-width: 900px;\n    margin: -30px auto 40px;\n    padding: 0 20px;\n    position: relative;\n}\n\n.feature {\n    background: white;\n    padding: 25px;\n    border-radius: 12px;\n    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.15);\n    text-align: center;\n}\n\n.feature h3 {\n    color: #6a1b9a;\n}"),

    lesson(34, $lv4so, $lv4ba, 'پرۆژە: بلۆگ لایۆت', 'پروژە: لایۆتا بلۆگێ',
        '<p>پرۆژە: لایۆتی بلۆگ:</p><ul><li>گرید: ناوەڕۆک (٢ بەش) + لاوەکی (١ بەش)</li><li>کارتی هەر پۆستێک</li><li>بەشی هەواڵە بەناوبانگەکان</li></ul><p>لایۆتی بلۆگ بۆ ناوەڕۆکی زۆر. گریدی ٢-٣ ستوونی بە minmax بۆ قەبارە جیاوازەکان.</p>',
        '<p>پروژە: لایۆتا بلۆگێ:</p><ul><li>گرید: ناڤەرۆک (٢ بەش) + لاوەکی (١ بەش)</li><li>کارتێن هەر پۆستەکێ</li><li>بەشا نڤیسارێن بەناڤ</li></ul><p>لایۆتا بلۆگێ بو ناڤەرۆکێ زێدە. گریدا ٢-٣ ستوونان پێ minmax بو قەبارێن جودا.</p>',
        ".blog-layout {\n    display: grid;\n    grid-template-columns: 1fr;\n    gap: 20px;\n    max-width: 1000px;\n    margin: 20px auto;\n    padding: 0 15px;\n}\n\n@media (min-width: 768px) {\n    .blog-layout {\n        grid-template-columns: 2fr 1fr;\n    }\n}\n\n.post-card {\n    background: white;\n    border-radius: 10px;\n    overflow: hidden;\n    margin-bottom: 20px;\n    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\n}\n\n.post-card img {\n    width: 100%;\n    height: 170px;\n    object-fit: cover;\n}\n\n.post-card h3 {\n    margin: 12px 15px 5px;\n}\n\n.post-card .meta {\n    color: #888;\n    font-size: 12px;\n    margin: 0 15px;\n}\n\n.post-card p {\n    color: #555;\n    margin: 10px 15px 15px;\n}\n\n.sidebar {\n    background: #fafafa;\n    border-radius: 10px;\n    padding: 15px;\n    align-self: start;\n}\n\n.sidebar h3 {\n    border-bottom: 2px solid #1976d2;\n    padding-bottom: 8px;\n}"),

    lesson(35, $lv4so, $lv4ba, 'پرۆژە: خشتەی نمرەکان جوان', 'پروژە: خشتا نمران جوان',
        '<p>پرۆژە: خشتەیەکی جوان بە CSS:</p><ul><li>سەری ڕەنگدار</li><li>ڕیزە یەکگرتووەکان (zebra)</li><li>دۆخی hover</li><li>نیشانەکانی دۆخ (یەکێک)</li></ul><p>خشتە بۆ زۆرترین داتا لە هەموو پەڕەیەک. بە <bdi>nth-child</bdi> ڕیزەکان یەکگرتوو ڕەنگ بکە و بە hover دیاری بکە.</p>',
        '<p>پروژە: خشتەکا جوان پێ CSS:</p><ul><li>سەرێ ڕەنگدار</li><li>ڕیزێن یەکگرتوو (zebra)</li><li>دۆخا hover</li><li>نیشانەکا دۆخی (ئێکێک)</li></ul><p>خشتە بو زێدەترین داتایێ د هەمی رووپەلان دا. پێ <bdi>nth-child</bdi> ڕیز یەکگرتوو ڕەنگ کە و پێ hover دیاری کە.</p>',
        "table {\n    width: 90%;\n    max-width: 700px;\n    margin: 30px auto;\n    border-collapse: collapse;\n    font-family: Arial;\n    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\n    border-radius: 10px;\n    overflow: hidden;\n}\n\nth {\n    background: #1565c0;\n    color: white;\n    padding: 14px;\n    text-align: right;\n}\n\ntd {\n    padding: 12px 14px;\n    border-bottom: 1px solid #eee;\n}\n\ntr:nth-child(even) {\n    background: #f5f8ff;\n}\n\ntr:hover {\n    background: #e3f2fd;\n}\n\n.status {\n    padding: 4px 12px;\n    border-radius: 20px;\n    font-size: 12px;\n}\n\n.status.pass {\n    background: #c8e6c9;\n    color: #1b5e20;\n}\n\n.status.fail {\n    background: #ffcdd2;\n    color: #b71c1c;\n}"),

    lesson(36, $lv4so, $lv4ba, 'پرۆژە: پۆرتەفۆلیۆ', 'پروژە: پۆرتەفۆلیۆ',
        '<p>پرۆژە: پۆرتەفۆلیۆ بە گرید:</p><ul><li>هەر کارتێک: وێنە + ناو + وەسف</li><li>hover بە ئەنیمەیشن</li><li>ڕیسپۆنسیڤ</li></ul><p>پۆرتەفۆلیۆ پیشاندانی کارەکانتە. کارتی سادە و ڕوون بە ئەفەکتێکی بچووک لەسەر hover.</p>',
        '<p>پروژە: پۆرتەفۆلیۆ پێ گرید:</p><ul><li>هەر کارتەک: وێنە + ناڤ + وەسف</li><li>hover پێ ئەنیمەیشن</li><li>ڕیسپۆنسیڤ</li></ul><p>پۆرتەفۆلیۆ نیشاندانا کارێن تە یە. کارتێن ساده و ڕوون پێ ئەفەکتەکا چویک ل سەر hover.</p>',
        ".portfolio {\n    display: grid;\n    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));\n    gap: 20px;\n    max-width: 1000px;\n    margin: 30px auto;\n    padding: 0 15px;\n}\n\n.project {\n    position: relative;\n    border-radius: 12px;\n    overflow: hidden;\n    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.15);\n}\n\n.project img {\n    width: 100%;\n    height: 200px;\n    object-fit: cover;\n    display: block;\n    transition: transform 0.4s;\n}\n\n.project:hover img {\n    transform: scale(1.1);\n}\n\n.project .overlay {\n    position: absolute;\n    inset: 0;\n    background: rgba(21, 101, 192, 0.85);\n    color: white;\n    display: flex;\n    flex-direction: column;\n    justify-content: center;\n    align-items: center;\n    opacity: 0;\n    transition: opacity 0.3s;\n}\n\n.project:hover .overlay {\n    opacity: 1;\n}\n\n.overlay h3 {\n    margin: 0;\n}\n\n.overlay p {\n    font-size: 13px;\n    opacity: 0.9;\n}"),

    lesson(37, $lv4so, $lv4ba, 'پرۆژە: وێبپەڕەی کۆمپانیا', 'پروژە: وێبپەڕەکا کۆمپانیایێ',
        '<p>پرۆژە: وێبپەڕەی کۆمپانیا. بەشەکان:</p><ul><li>ناڤیگەیشنی سەرەوە</li><li>پێشوازی + دوگمەی کردار</li><li>خزمەتگوزارییەکان (٣ کارت)</li><li>تیم + پەیوەندیکردن</li></ul><p>بۆ کۆمپانیا، متمانە و پیشەیی زۆر گرنگە: ڕەنگە نەرم و ڕێکوپێک و فۆنتی ڕوون.</p>',
        '<p>پروژە: وێبپەڕەکا کۆمپانیایێ. بەش:</p><ul><li>ناڤیگەیشنا سەرەوێ</li><li>پێشوازی + دوگمەیا کردارێ</li><li>خزمەتگوزاری (٣ کارت)</li><li>تیم + پەیوەندی</li></ul><p>بو کۆمپانیا، پشتەوەدان و پیشەیی زۆر گرنگە: ڕەنگێن نەرم و ڕێکوپێک و فۆنتەکا ڕوون.</p>',
        ".navbar {\n    display: flex;\n    justify-content: space-between;\n    padding: 18px 30px;\n    background: white;\n    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);\n    font-family: Arial;\n}\n\n.navbar .logo {\n    font-weight: bold;\n    font-size: 20px;\n    color: #263238;\n}\n\n.navbar a {\n    color: #455a64;\n    text-decoration: none;\n    margin-left: 18px;\n}\n\n.hero {\n    text-align: center;\n    padding: 80px 20px;\n    background: #f5f7fa;\n}\n\n.hero h1 {\n    font-size: 40px;\n    color: #263238;\n    margin: 0 0 10px;\n}\n\n.hero p {\n    color: #607d8b;\n    margin: 0 auto 25px;\n    max-width: 500px;\n}\n\n.hero .btn {\n    background: #1976d2;\n    color: white;\n    padding: 12px 30px;\n    border-radius: 6px;\n    text-decoration: none;\n}\n\n.services {\n    display: grid;\n    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));\n    gap: 20px;\n    max-width: 900px;\n    margin: 40px auto;\n    padding: 0 15px;\n}\n\n.service {\n    background: white;\n    border: 1px solid #e0e0e0;\n    border-radius: 10px;\n    padding: 25px;\n    text-align: center;\n}\n\n.service .icon {\n    font-size: 36px;\n}"),

    lesson(38, $lv4so, $lv4ba, 'پرۆژە: وێبسایتێکی تەواو - بەشی ١', 'پروژە: وێبسایتەکا تەمام - بەش ١',
        '<p>پرۆژەی کۆتایی: وێبسایتێکی تەواو بە ٣ بەش. بەشی یەکەم:</p><ul><li>ناڤیگەیشنی سەرەوە (ڕەنگ + hover + active)</li><li>بەشی پێشوازی (hero) بە گرادینت</li><li>بۆشایی و padding</li></ul><p>بنەڕەتی وەرگره: رنگ + فۆنت + بۆشایی. لە بەشەکانی داهاتوودا بەشەکانی تر زیاد دەکەین.</p>',
        '<p>پروژەیا دویاهین: وێبسایتەکا تەمام ب ٣ بەش. بەشێ یەکێ:</p><ul><li>ناڤیگەیشنا سەرەوێ (ڕەنگ + hover + active)</li><li>بەشا پێشوازیێ (hero) پێ گرادینت</li><li>بۆشایی و padding</li></ul><p>بنگەهێ بگره: ڕەنگ + فۆنت + بۆشایی. د بەشێن داهاتێ دا بەشێن دی زێدە دکەین.</p>',
        "* { box-sizing: border-box; }\n\nbody {\n    margin: 0;\n    font-family: Arial, sans-serif;\n    color: #263238;\n}\n\n.navbar {\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n    background: #263238;\n    color: white;\n    padding: 0 30px;\n}\n\n.navbar .logo {\n    font-size: 24px;\n    font-weight: bold;\n    color: #ffd54f;\n}\n\n.navbar ul {\n    display: flex;\n    list-style: none;\n    margin: 0;\n    padding: 0;\n}\n\n.navbar a {\n    display: block;\n    color: white;\n    text-decoration: none;\n    padding: 18px 15px;\n    transition: background 0.2s;\n}\n\n.navbar a:hover,\n.navbar a.active {\n    background: #1976d2;\n}\n\n.hero {\n    background: linear-gradient(135deg, #1976d2, #42a5f5);\n    color: white;\n    text-align: center;\n    padding: 100px 20px;\n}\n\n.hero h1 {\n    font-size: 46px;\n    margin: 0 0 12px;\n}\n\n.hero p {\n    font-size: 18px;\n    opacity: 0.95;\n    max-width: 550px;\n    margin: 0 auto;\n}\n\n.hero .btn {\n    display: inline-block;\n    margin-top: 30px;\n    background: white;\n    color: #1976d2;\n    padding: 14px 35px;\n    border-radius: 30px;\n    text-decoration: none;\n    font-weight: bold;\n}"),

    lesson(39, $lv4so, $lv4ba, 'پرۆژە: وێبسایتێکی تەواو - بەشی ٢', 'پروژە: وێبسایتەکا تەمام - بەش ٢',
        '<p>بەشی دووەم: بەشەکانی ناوەڕۆک:</p><ul><li>بەشی دەربارەی کۆمپانیا</li><li>کارتی خزمەتگوزارییەکان (گرید)</li><li>بەشی تیم</li></ul><p>هەر بەشێک <bdi>section</bdi> بە <bdi>padding</bdi>ی گەورە و ناونیشانی ڕوون. کارتەکان بە <bdi>minmax</bdi> ڕیسپۆنسیڤ.</p>',
        '<p>بەشێ دویێ: بەشێن ناڤەرۆکی:</p><ul><li>بەشا دەربارە کۆمپانیایێ</li><li>کارتێن خزمەتگوزاریان (گرید)</li><li>بەشا تیمێ</li></ul><p>هەر بەشەک <bdi>section</bdi> پێ <bdi>padding</bdi>یا مەزن و ناڤەکا ڕوون. کارت پێ <bdi>minmax</bdi> ڕیسپۆنسیڤ.</p>',
        ".about {\n    padding: 80px 20px;\n    text-align: center;\n    max-width: 800px;\n    margin: auto;\n}\n\n.about h2 {\n    font-size: 32px;\n}\n\n.services {\n    background: #f5f7fa;\n    padding: 70px 20px;\n    text-align: center;\n}\n\n.services h2 {\n    font-size: 32px;\n    margin-bottom: 35px;\n}\n\n.cards {\n    display: grid;\n    grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));\n    gap: 20px;\n    max-width: 950px;\n    margin: auto;\n}\n\n.card {\n    background: white;\n    border-radius: 12px;\n    padding: 30px;\n    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.08);\n    transition: transform 0.3s;\n}\n\n.card:hover {\n    transform: translateY(-5px);\n}\n\n.card .icon {\n    font-size: 40px;\n}\n\n.card h3 {\n    color: #1976d2;\n}\n\n.team {\n    padding: 70px 20px;\n    text-align: center;\n}\n\n.team-cards {\n    display: flex;\n    flex-wrap: wrap;\n    justify-content: center;\n    gap: 25px;\n}\n\n.member img {\n    width: 100px;\n    height: 100px;\n    border-radius: 50%;\n    object-fit: cover;\n}\n\n.member p {\n    color: #888;\n    font-size: 14px;\n}"),

    lesson(40, $lv4so, $lv4ba, 'پرۆژە: وێبسایتێکی تەواو - بەشی ٣', 'پروژە: وێبسایتەکا تەمام - بەش ٣',
        '<p>بەشی کۆتایی: فۆڕمی پەیوەندیکردن، دواوە، و ڕیسپۆنسیڤ:</p><ul><li>فۆڕم بە ستایلی باش</li><li>footer بە لینکەکان</li><li>media query بۆ موبایل</li><li>ئەنیمەیشن بچووک</li></ul><p>ئێستا وێبسایتەکەت تەواوە! هەموو تایبەتمەندییەکانت لە بەشەکانی پێشوودا بەکاربهێنە و پێشکەشی هاوڕێکانت بکە.</p>',
        '<p>بەشێ دویاهین: فۆرما پەیوەندیێ، دویاهیا، و ڕیسپۆنسیڤ:</p><ul><li>فۆرم پێ ستایلەکا باش</li><li>footer پێ گرێدانان</li><li>media query بو mobayl</li><li>ئەنیمەیشنەکا چویک</li></ul><p>نڤها وێبسایتا تە تەمامە! هەمی تایبەتمەندییێن خوە د بەشێن بەری دا بکاربینی و پێشکەشی هەڤالێن خوە بکە.</p>',
        ".contact {\n    background: #f5f7fa;\n    padding: 70px 20px;\n    text-align: center;\n}\n\n.contact form {\n    max-width: 400px;\n    margin: auto;\n    text-align: right;\n}\n\n.contact input,\n.contact textarea {\n    width: 100%;\n    padding: 12px;\n    border: 1px solid #ccc;\n    border-radius: 6px;\n    margin: 6px 0 14px;\n    box-sizing: border-box;\n}\n\n.contact textarea {\n    height: 100px;\n}\n\n.contact button {\n    width: 100%;\n    background: #1976d2;\n    color: white;\n    border: none;\n    padding: 13px;\n    border-radius: 6px;\n    font-size: 15px;\n    cursor: pointer;\n}\n\nfooter {\n    background: #263238;\n    color: #bbb;\n    text-align: center;\n    padding: 25px;\n}\n\nfooter a {\n    color: #ffd54f;\n    text-decoration: none;\n    margin: 0 8px;\n}\n\n@media (max-width: 600px) {\n    .navbar {\n        flex-direction: column;\n    }\n    .navbar ul {\n        width: 100%;\n        flex-direction: column;\n        text-align: center;\n    }\n    .hero h1 {\n        font-size: 30px;\n    }\n    .hero {\n        padding: 60px 15px;\n    }\n}\n\n@keyframes fadeUp {\n    from { opacity: 0; transform: translateY(15px); }\n    to   { opacity: 1; transform: translateY(0); }\n}\n\n.hero {\n    animation: fadeUp 0.8s ease-out;\n}"),
];

foreach ($lessons as $lesson) {
    $lesson['langId'] = $langId;
    $res = fbPost($firebaseUrl . 'ferga_lessons.json', $lesson);
    $d = json_decode($res, true);
    if (isset($d['name'])) {
        echo "Lesson added: {$lesson['title_so']} -> {$d['name']}\n";
    } else {
        echo "ERROR adding lesson {$lesson['title_so']}: $res\n";
    }
}

echo "\nDone! CSS lessons 21-40 added.\n";
