<?php

// Script to add HTML lessons 21-40 to the Ferga section in Firebase
$firebaseUrl = 'https://ai-platform-adb1b-default-rtdb.firebaseio.com/';
$idToken = trim(file_get_contents('/tmp/opencode/fb_token.txt'));
$langId = '-OysQq7E9B4bBLuGjUEX';

function fbPost($url, $data) {
    global $idToken;
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Authorization: Bearer ' . $idToken, 'Content-Type: application/json']);
    $res = curl_exec($ch);
    curl_close($ch);
    return $res;
}

function lesson($order, $level_so, $level_ba, $title_so, $title_ba, $content_so, $content_ba, $code) {
    return [
        'order' => $order,
        'level_so' => $level_so,
        'level_ba' => $level_ba,
        'title_so' => $title_so,
        'title_ba' => $title_ba,
        'content_so' => $content_so,
        'content_ba' => $content_ba,
        'code' => $code,
        'example_output' => '',
        'challenge_desc_so' => '',
        'challenge_desc_ba' => '',
        'expected_output' => '',
    ];
}

$lv3so = 'ئاستی ٣ - تایبەتمەندی و پێشکەوتوو';
$lv3ba = 'ئاستا ٣ - تایبەتمەندی و پێشکەفتی';
$lv4so = 'ئاستی ٤ - پرۆژەکان';
$lv4ba = 'ئاستا ٤ - پروژە';

$lessons = [
    lesson(21, $lv3so, $lv3ba, 'SVG و کانڤاس', 'SVG و کانڤاس',
        '<p><bdi>&lt;svg&gt;</bdi> وێنەی ڤێکتۆری دروست دەکات لە ناو HTML و <bdi>&lt;canvas&gt;</bdi> وێنە بە JavaScript کێش دەکات:</p><pre>&lt;svg width="100" height="100"&gt;\n  &lt;circle cx="50" cy="50" r="40" fill="green"/&gt;\n&lt;/svg&gt;</pre><p>SVG بۆ ئایکۆن و شێوە سادەکان باشە، canvas بۆ یاری و گرافیکی ئاڵۆز.</p>',
        '<p><bdi>&lt;svg&gt;</bdi> وێنەیێن ڤێکتۆری د ناڤ HTML دا دروست دکەت و <bdi>&lt;canvas&gt;</bdi> وێنە پێ JavaScript کێش دکەت:</p><pre>&lt;svg width="100" height="100"&gt;\n  &lt;circle cx="50" cy="50" r="40" fill="green"/&gt;\n&lt;/svg&gt;</pre><p>SVG بو ئایکۆن و شێوەیێن ساده باشە، canvas بو یاری و گرافیکا تەڤلیی.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <title>SVG u Canvas</title>\n</head>\n<body>\n  <h3>SVG</h3>\n  <svg width=\"120\" height=\"120\">\n    <rect x=\"10\" y=\"10\" width=\"100\" height=\"70\" rx=\"10\" fill=\"#4caf50\"/>\n    <circle cx=\"60\" cy=\"80\" r=\"25\" fill=\"#ff9800\"/>\n  </svg>\n  <h3>Canvas</h3>\n  <canvas id=\"c\" width=\"200\" height=\"100\" style=\"border:1px solid #333\"></canvas>\n  <script>\n    const c = document.getElementById(\"c\");\n    const ctx = c.getContext(\"2d\");\n    ctx.fillStyle = \"#2196f3\";\n    ctx.fillRect(20, 20, 150, 50);\n  </script>\n</body>\n</html>"),

    lesson(22, $lv3so, $lv3ba, 'فیلدست و لیجێند', 'فیلدست و لیجێند',
        '<p><bdi>&lt;fieldset&gt;</bdi> بەشی فۆڕمەکە لە کۆنترۆڵ دەگرێت و <bdi>&lt;legend&gt;</bdi> ناونیشانی ئەو بەشەیە:</p><pre>&lt;fieldset&gt;\n  &lt;legend&gt;Agahiyên kesane&lt;/legend&gt;\n  ...inputs...\n&lt;/fieldset&gt;</pre><p>فۆڕمی درێژ بۆ بەشە بچووکەکان دابەش بکە بۆ فەهمی باشتر. ئەتریبیوتی <bdi>disabled</bdi> هەموو بەشەکە دەکاتە ناچالاک.</p>',
        '<p><bdi>&lt;fieldset&gt;</bdi> پارچەکا فۆرمێ د گرتنا خوە دا دگریت و <bdi>&lt;legend&gt;</bdi> ناڤێ وی پارچەیێ یە:</p><pre>&lt;fieldset&gt;\n  &lt;legend&gt;Agahiyên kesane&lt;/legend&gt;\n  ...inputs...\n&lt;/fieldset&gt;</pre><p>فۆرمێن درێژ بو پارچەیێن چویک دابەش کە بو تێگەهشتنەکا باشتر. ئەتریبیوتا <bdi>disabled</bdi> هەمی پارچە ناچالاک دکەت.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <title>Fieldset</title>\n</head>\n<body>\n  <form>\n    <fieldset style=\"border:2px solid #4caf50; border-radius:8px\">\n      <legend style=\"color:#4caf50\">Agahiyên kesane</legend>\n      <label>Nav: <input type=\"text\" name=\"nav\"></label>\n      <br><br>\n      <label>E-mail: <input type=\"email\" name=\"email\"></label>\n    </fieldset>\n    <br>\n    <fieldset style=\"border:2px solid #2196f3; border-radius:8px\">\n      <legend style=\"color:#2196f3\">Karerêkirin</legend>\n      <label>Ziman: <input type=\"text\" name=\"ziman\" value=\"HTML\"></label>\n      <br><br>\n      <input type=\"submit\" value=\"Tomar kirin\">\n    </fieldset>\n  </form>\n</body>\n</html>"),

    lesson(23, $lv3so, $lv3ba, 'ناڤیگەیشنی وێبسایت', 'ناڤیگەیشنا وێبسایتێ',
        '<p><bdi>&lt;nav&gt;</bdi> بۆ ناڤیگەیشنی وێبسایتەکە، زۆرجار لەگەڵ لیستی لینکەکان:</p><pre>&lt;nav&gt;\n  &lt;ul&gt;\n    &lt;li&gt;&lt;a href=\"#\"&gt;Mal&lt;/a&gt;&lt;/li&gt;\n    &lt;li&gt;&lt;a href=\"#kurs\"&gt;Kurs&lt;/a&gt;&lt;/li&gt;\n  &lt;/ul&gt;\n&lt;/nav&gt;</pre><p>لە CSS دەتوانیت ڕەوانەی لینکەکان دیاری بکەیت. بۆ ئەنکەرەکان <bdi>#id</bdi> بەکاربهێنە. ناڤیگەیشن دەبێت سادە و ڕوون بێت.</p>',
        '<p><bdi>&lt;nav&gt;</bdi> بو ناڤیگەیشنا وێبسایتێ، پشتیا ڤە پێ لیستا گرێدانان:</p><pre>&lt;nav&gt;\n  &lt;ul&gt;\n    &lt;li&gt;&lt;a href=\"#\"&gt;Mal&lt;/a&gt;&lt;/li&gt;\n    &lt;li&gt;&lt;a href=\"#kurs\"&gt;Kurs&lt;/a&gt;&lt;/li&gt;\n  &lt;/ul&gt;\n&lt;/nav&gt;</pre><p>د CSS دا دکەی ڕوخسارا گرێدانان دیاری کەی. بو ئەنکەران <bdi>#id</bdi> بکاربینی. ناڤیگەیشن دڤێت ساده و ڕوون بیت.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <title>Navigation</title>\n  <style>\n    nav ul { list-style: none; background: #333; padding: 0; }\n    nav li { display: inline; }\n    nav a { color: white; text-decoration: none; padding: 10px 20px; display: inline-block; }\n    nav a:hover { background: #4caf50; }\n  </style>\n</head>\n<body>\n  <nav>\n    <ul>\n      <li><a href=\"#\">Mal</a></li>\n      <li><a href=\"#kurs\">Kurs</a></li>\n      <li><a href=\"#têkilî\">Têkilî</a></li>\n    </ul>\n  </nav>\n  <h1 id=\"kurs\">Kurs</h1>\n  <p>Naveroka kursan...</p>\n</body>\n</html>"),

    lesson(24, $lv3so, $lv3ba, 'وێبئەکسیبلیتی (Accessibility)', 'وێبئەکسیبلیتی',
        '<p>وێبئەکسیبلیتی واتە هەموو کەسێک، لەوانە کەمی ئەندام، بتوانێت پەڕەکە بەکاربهێنێت:</p><ul><li><bdi>alt</bdi> بۆ هەموو وێنەکان</li><li><bdi>&lt;label for&gt;</bdi> بۆ هەموو فۆڕمەکان</li><li><bdi>aria-label</bdi> بۆ دوگمەکانی ئایکۆن</li><li>پەیوەندی ڕەنگ و کۆنتراستی باش</li><li>قەبارەی فۆنت گەورە</li></ul><p>بۆ تاقە سێمەنتیکەکان و سەرنووسە ڕێکوپێکەکان بەکاربهێنە.</p>',
        '<p>وێبئەکسیبلیتی واتە هەمی کەس، تەڤی کەمئەندام، دکەت رووپەلێ بکاربینیت:</p><ul><li><bdi>alt</bdi> بو هەمی وێنەیان</li><li><bdi>&lt;label for&gt;</bdi> بو هەمی فۆرمان</li><li><bdi>aria-label</bdi> بو دوگمەیێن ئایکۆنی</li><li>پەیوەندی و کۆنتراستا ڕەنگان باش</li><li>قەبارا فۆنتی مەزن</li></ul><p>تاگێن سێمەنتیک و سەردێڕێن ڕێک بکاربینی.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <title>Accessibility</title>\n</head>\n<body>\n  <header>\n    <h1>Rûpeleke bigihîjbar</h1>\n  </header>\n  <main>\n    <img src=\"https://picsum.photos/200/120\" alt=\"Wêneyekî piştgirî\">\n    <form>\n      <label for=\"nav\">Navê te:</label>\n      <input type=\"text\" id=\"nav\" name=\"nav\">\n      <br><br>\n      <button type=\"submit\" aria-label=\"Şandina formê\">\u2764 Şandin</button>\n    </form>\n  </main>\n</body>\n</html>"),

    lesson(25, $lv3so, $lv3ba, 'تێکستی RTL و LTR', 'نڤیسینا RTL و LTR',
        '<p>ئەتریبیوتی <bdi>dir</bdi> ئاراستەی دەق دیاری دەکات: <bdi>rtl</bdi> (ڕاست بۆ چەپ) یان <bdi>ltr</bdi> (چەپ بۆ ڕاست):</p><pre>&lt;p dir=\"rtl\"&gt;Ev nivîsa kurdî ye&lt;/p&gt;</pre><p>بۆ تێکەڵی دەقی لاتینی و کوردی بەیەکدا (وەک کۆد)، تاقی <bdi>&lt;bdi&gt;</bdi> یان <bdi>&lt;bdo&gt;</bdi> بەکاربهێنە بۆ ئەوەی ئاراستەکە بە هەڵە نیشان نەدرێت.</p>',
        '<p>ئەتریبیوتا <bdi>dir</bdi> ئاراستەیا نڤیسینێ دیاری دکەت: <bdi>rtl</bdi> (راست بۆ چەپ) یا <bdi>ltr</bdi> (چەپ بۆ راست):</p><pre>&lt;p dir=\"rtl\"&gt;Ev nivîsa kurdî ye&lt;/p&gt;</pre><p>بو تێکەلکرنا نڤیسینا لاتینی و کوردی پێکڤە (وەک کۆد)، تاگێ <bdi>&lt;bdi&gt;</bdi> یا <bdi>&lt;bdo&gt;</bdi> بکاربینی دا ئاراستە ب شێوەیەکا خەلەت نیشان نەدریت.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <title>RTL u LTR</title>\n</head>\n<body>\n  <p dir=\"rtl\">ئەم دەقە لە ڕاستەوە دەخوێنرێتەوە.</p>\n  <p dir=\"ltr\">This text is read from left to right.</p>\n  <p>Zimanê <bdi>HTML</bdi> ji bo her du aliyan e.</p>\n</body>\n</html>"),

    lesson(26, $lv3so, $lv3ba, 'دیتالیست و ئۆتیۆکۆمپلیت', 'دیتالیست و ئۆتیۆکۆمپلیت',
        '<p><bdi>&lt;datalist&gt;</bdi> پێشنیاری نووسین بۆ خانەیەکی input دابین دەکات:</p><pre>&lt;input list=\"bajar\" name=\"bajar\"&gt;\n&lt;datalist id=\"bajar\"&gt;\n  &lt;option value=\"Hewlêr\"&gt;\n  &lt;option value=\"Silêmanî\"&gt;\n&lt;/datalist&gt;</pre><p>بەکارهێنەر دەتوانێت لە لیستەکە هەڵبژێرێت یان بەها تایبەتەکەی خۆی بنووسێت. ئەتریبیوتی <bdi>list</bdi> ی input دەبێت یەکسان بێت بە <bdi>id</bdi> ی datalist.</p>',
        '<p><bdi>&lt;datalist&gt;</bdi> پێشنیارێن نڤیسینێ بو خانەیا input دابین دکەت:</p><pre>&lt;input list=\"bajar\" name=\"bajar\"&gt;\n&lt;datalist id=\"bajar\"&gt;\n  &lt;option value=\"Hewlêr\"&gt;\n  &lt;option value=\"Silêmanî\"&gt;\n&lt;/datalist&gt;</pre><p>بکارهێنەر دکەت ژ لیستێ هەلبژیریت یا بەها تایبەتا خوە بنڤیسیت. ئەتریبیوتا <bdi>list</bdi> یا input دڤێت یەکسان بیت پێ <bdi>id</bdi> یا datalist.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <title>Datalist</title>\n</head>\n<body>\n  <h3>Bajarê xwe hilbijêre</h3>\n  <input list=\"bajar\" name=\"bajar\" placeholder=\"Bajarek binivîse\">\n  <datalist id=\"bajar\">\n    <option value=\"Hewlêr\">\n    <option value=\"Silêmanî\">\n    <option value=\"Dihok\">\n    <option value=\"Hewlamb\" selected>\n  </datalist>\n</body>\n</html>"),

    lesson(27, $lv3so, $lv3ba, 'ڤالیدەیشنی فۆڕم', 'ڤالیدەکرنا فۆرمێ',
        '<p>HTML5 پشتڕاستکردنەوەی خۆکارانە بۆ فۆڕمەکان هەیە:</p><ul><li><bdi>required</bdi> - خانەکە دەبێت پڕ بێت</li><li><bdi>min</bdi> / <bdi>max</bdi> - سنووری ژمارە</li><li><bdi>minlength</bdi> / <bdi>maxlength</bdi> - درێژی دەق</li><li><bdi>pattern</bdi> - شێوازی دەقی ڕێگەپێدراو</li></ul><p>کاتێک داتاکە نادروستە، وێبگەڕەکە پەیامی هەڵە نیشان دەدات و فۆڕمەکە نانێردرێت.</p>',
        '<p>HTML5 پشتڕاستکرنا خودکار بو فۆرمان هەیە:</p><ul><li><bdi>required</bdi> - خانە دڤێت تیژ بیت</li><li><bdi>min</bdi> / <bdi>max</bdi> - سنوورێن ژمارەیێ</li><li><bdi>minlength</bdi> / <bdi>maxlength</bdi> - درێژەهاتنا نڤیسینێ</li><li><bdi>pattern</bdi> - شێوازا نڤیسینا دەستپێگهیشتی</li></ul><p>دەمە کو داتا نە دروستە، وێبگەر پەیاما خەلەتی نیشان ددەت و فۆرم نا شاندیت.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <title>Validation</title>\n</head>\n<body>\n  <h3>Forma qeydkirinê</h3>\n  <form>\n    <label>Nav (kêmtir 3 tîp):\n      <input type=\"text\" name=\"nav\" required minlength=\"3\">\n    </label>\n    <br><br>\n    <label>E-mail:\n      <input type=\"email\" name=\"email\" required>\n    </label>\n    <br><br>\n    <label>Sal (18-60):\n      <input type=\"number\" name=\"sal\" min=\"18\" max=\"60\" required>\n    </label>\n    <br><br>\n    <label>Telefon:\n      <input type=\"tel\" name=\"tel\" pattern=\"[0-9]{10}\" placeholder=\"0712345678\" required>\n    </label>\n    <br><br>\n    <input type=\"submit\" value=\"Qeyd kirin\">\n  </form>\n</body>\n</html>"),

    lesson(28, $lv4so, $lv4ba, 'پرۆژە: وێبپەڕەی کەسی', 'پروژە: وێبپەڕەکا کەسی',
        '<p>یەکەم پرۆژە: وێبپەڕەیەکی کەسی دروست بکە. تێیدا دەبێت:</p><ul><li>وێنەی پڕۆفایل و ناو</li><li>بەشی دەربارەی من</li><li>لیستی شارەزاییەکان</li><li>لینکی تۆڕە کۆمەڵایەتییەکان</li></ul><p>بەشەکانی <bdi>header</bdi>، <bdi>main</bdi> و <bdi>footer</bdi> بەکاربهێنە. وێنەی خۆت دەتوانیت بە وێنەی سەرەکی لە <bdi>picsum.photos</bdi> بگۆڕیت.</p>',
        '<p>پروژەیا دویێ: وێبپەڕەکا کەسی دروست کە. د ناڤ وی دا دڤێت:</p><ul><li>وێنەیا پڕۆفایلێ و ناڤ</li><li>بەشا دەربارە من</li><li>لیستا زانینان (شارەزاییان)</li><li>گرێدانێن تۆڕێن کۆمەلایەتی</li></ul><p>بەشێن <bdi>header</bdi>، <bdi>main</bdi> و <bdi>footer</bdi> بکاربینی. وێنەیا خوە دکەی پێ وێنەیا سەرەکی ژ <bdi>picsum.photos</bdi> بگوهۆڕی.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Rêzan - Rûpela Kesane</title>\n  <style>\n    body { font-family: Arial; margin: 0; background: #f5f5f5; text-align: center; }\n    header { background: #263238; color: white; padding: 30px; }\n    img.avatar { border-radius: 50%; width: 130px; border: 4px solid #4caf50; }\n    section { background: white; margin: 20px auto; padding: 20px; max-width: 500px; border-radius: 10px; }\n    ul { list-style: none; padding: 0; }\n    li { background: #e8f5e9; margin: 5px; padding: 8px; border-radius: 5px; }\n    footer { background: #263238; color: #bbb; padding: 15px; margin-top: 20px; }\n  </style>\n</head>\n<body>\n  <header>\n    <img class=\"avatar\" src=\"https://picsum.photos/130\" alt=\"Wêneyê Rêzan\">\n    <h1>Rêzan Ehmed</h1>\n    <p>Xwendekarê programkirinê</p>\n  </header>\n  <main>\n    <section>\n      <h2>Der barê min</h2>\n      <p>Ez ji Hewlêrê me û dixwazim bibim web developer.</p>\n    </section>\n    <section>\n      <h2>Şarezayiyên min</h2>\n      <ul>\n        <li>HTML</li>\n        <li>CSS</li>\n        <li>Python</li>\n      </ul>\n    </section>\n    <section>\n      <h2>Têkiliyên min</h2>\n      <p><a href=\"https://github.com\">GitHub</a> | <a href=\"https://instagram.com\">Instagram</a></p>\n    </section>\n  </main>\n  <footer>\n    <p>© 2026 Rêzan</p>\n  </footer>\n</body>\n</html>"),

    lesson(29, $lv4so, $lv4ba, 'پرۆژە: بلۆگ', 'پروژە: بلۆگ',
        '<p>پرۆژەی بلۆگ: لیستی بابەتەکان لەگەڵ بەروار و خوێنەری:</p><ul><li>بەشی <bdi>&lt;article&gt;</bdi> بۆ هەر بابەتێک</li><li>سەرنووسە، دەق و لینکی خوێندنەوە</li><li>بەروار و ناوی نووسەر</li></ul><p>بابەتەکان بە <bdi>&lt;h2&gt;</bdi> و بەشەکان بە <bdi>&lt;h3&gt;</bdi> ڕێک بخە.</p>',
        '<p>پروژەیا بلۆگێ: لیستا بابەتان پێکڤە پێ دیرۆک و خواندنی:</p><ul><li>بەشا <bdi>&lt;article&gt;</bdi> بو هەر بابەتەکێ</li><li>سەردێڕ، دەق و گرێدانا خواندنێ</li><li>دیرۆک و ناڤێ نڤیسنەر</li></ul><p>بابەت پێ <bdi>&lt;h2&gt;</bdi> و بەش پێ <bdi>&lt;h3&gt;</bdi> ڕێک بخە.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Bloga Min</title>\n  <style>\n    body { font-family: Arial; margin: 0; background: #fafafa; }\n    header { background: #7b1fa2; color: white; padding: 20px 30px; }\n    main { max-width: 700px; margin: 20px auto; padding: 0 15px; }\n    article { background: white; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0 2px 5px #ddd; }\n    .meta { color: #999; font-size: 13px; }\n    a { color: #7b1fa2; }\n  </style>\n</head>\n<body>\n  <header>\n    <h1>Bloga Rêzan</h1>\n  </header>\n  <main>\n    <article>\n      <h2>Destpêka HTML</h2>\n      <p class=\"meta\">12 Gulan 2026 - Rêzan</p>\n      <p>HTML bingeha her malperê ye...</p>\n      <a href=\"#\">Bixwîne</a>\n    </article>\n    <article>\n      <h2>5 serişteyên CSS</h2>\n      <p class=\"meta\">10 Gulan 2026 - Rêzan</p>\n      <p>Bi van serişteyan malpera xwe bedew bike...</p>\n      <a href=\"#\">Bixwîne</a>\n    </article>\n  </main>\n</body>\n</html>"),

    lesson(30, $lv4so, $lv4ba, 'پرۆژە: پەڕەی کانتاکت', 'پروژە: رووپەڵا کانتاکت',
        '<p>پرۆژە: پەڕەی پەیوەندیکردن (کانتاکت). تێیدا دەبێت:</p><ul><li>فۆڕمی تەواو: ناو، ئیمەیڵ، بابەت، پەیام</li><li>بەشی <bdi>fieldset</bdi> و <bdi>legend</bdi></li><li>ڤالیدەیشنی HTML5 (<bdi>required</bdi>)</li><li>دەق و select</li></ul><p>ئەم پەڕەیەش لەگەڵ HTML و CSS بێ JavaScript دەبێت.</p>',
        '<p>پروژە: رووپەڵا پەیوەندیێ (کانتاکت). د ناڤ دا دڤێت:</p><ul><li>فۆرمەکا تەمام: ناڤ، ئیمەیڵ، بابەت، پەیام</li><li>بەشا <bdi>fieldset</bdi> و <bdi>legend</bdi></li><li>ڤالیدەکرنا HTML5 (<bdi>required</bdi>)</li><li>دەق و select</li></ul><p>ئەڤ رووپەلە هەر پێ HTML و CSS بێ JavaScript دبیت.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Têkilî</title>\n  <style>\n    body { font-family: Arial; background: #eef2f7; }\n    form { max-width: 500px; margin: 30px auto; background: white; padding: 25px; border-radius: 10px; }\n    label { display: block; margin: 12px 0 4px; }\n    input, select, textarea { width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box; }\n    button { background: #1976d2; color: white; border: none; padding: 10px 25px; margin-top: 15px; border-radius: 5px; }\n  </style>\n</head>\n<body>\n  <form>\n    <h2>Têkiliyê bi me re</h2>\n    <fieldset>\n      <legend>Agahiyên te</legend>\n      <label for=\"nav\">Nav</label>\n      <input type=\"text\" id=\"nav\" name=\"nav\" required>\n      <label for=\"email\">E-mail</label>\n      <input type=\"email\" id=\"email\" name=\"email\" required>\n    </fieldset>\n    <fieldset>\n      <legend>Peyam</legend>\n      <label for=\"babet\">Babet</label>\n      <select id=\"babet\" name=\"babet\">\n        <option>Pirsên kursan</option>\n        <option>Pêşniyar</option>\n        <option>Hevkarî</option>\n      </select>\n      <label for=\"peyam\">Peyam</label>\n      <textarea id=\"peyam\" name=\"peyam\" rows=\"5\" required></textarea>\n    </fieldset>\n    <button type=\"submit\">Bisîne</button>\n  </form>\n</body>\n</html>"),

    lesson(31, $lv4so, $lv4ba, 'پرۆژە: گالەری وێنە', 'پروژە: گالەریا وێنەیان',
        '<p>پرۆژە: گالەری وێنە. وێنەکان بە تۆڕی grid نیشان بدە:</p><ul><li>چەند وێنە بە <bdi>picsum.photos</bdi></li><li>هەر وێنەیەک لە ناو <bdi>&lt;figure&gt;</bdi></li><li><bdi>&lt;figcaption&gt;</bdi> بۆ ناونیشان</li><li>ستایلی grid لە CSS</li></ul><p>هەر وێنەیەک <bdi>alt</bdi> ی دروست بێت.</p>',
        '<p>پروژە: گالەریا وێنەیان. وێنە پێ تۆڕا grid نیشان بدە:</p><ul><li>چەند وێنە پێ <bdi>picsum.photos</bdi></li><li>هەر وێنەکا د ناڤ <bdi>&lt;figure&gt;</bdi> دا</li><li><bdi>&lt;figcaption&gt;</bdi> بو ناڤان</li><li>ستایلا grid د CSS دا</li></ul><p>هەر وێنەکا <bdi>alt</bdi> یا دروست بیت.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Galerya Wêneyan</title>\n  <style>\n    body { font-family: Arial; background: #222; color: white; text-align: center; }\n    .galery { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; padding: 20px; max-width: 900px; margin: auto; }\n    figure { margin: 0; background: #333; border-radius: 8px; padding: 8px; }\n    img { width: 100%; border-radius: 5px; }\n    figcaption { margin-top: 6px; font-size: 14px; }\n  </style>\n</head>\n<body>\n  <h1>Galerya Kurdistanê</h1>\n  <div class=\"galery\">\n    <figure><img src=\"https://picsum.photos/300/200?1\" alt=\"Wêneyê 1\"><figcaption>Çiyayên Kurmênc</figcaption></figure>\n    <figure><img src=\"https://picsum.photos/300/200?2\" alt=\"Wêneyê 2\"><figcaption>Deşt</figcaption></figure>\n    <figure><img src=\"https://picsum.photos/300/200?3\" alt=\"Wêneyê 3\"><figcaption>Ava Vî</figcaption></figure>\n    <figure><img src=\"https://picsum.photos/300/200?4\" alt=\"Wêneyê 4\"><figcaption>Keleha Hewlamb</figcaption></figure>\n  </div>\n</body>\n</html>"),

    lesson(32, $lv4so, $lv4ba, 'پرۆژە: خشتەی نمرەکان', 'پروژە: خشتا نمران',
        '<p>پرۆژە: خشتەی نمرەکانی قوتابیان. تێیدا دەبێت:</p><ul><li>ستوونەکان: ناو، کۆرس، نمرە، ئەنجام</li><li><bdi>colspan</bdi> بۆ یەکگرتنی خانە</li><li>ڕیزێک بۆ کۆی گشتی</li><li>ستایلی خشتە لە CSS</li></ul><p>بە <bdi>rowspan</bdi> دەتوانیت ڕیزەکانی پێکەوە ببەستیتەوە.</p>',
        '<p>پروژە: خشتا نمران قوتابیان. د ناڤ دا دڤێت:</p><ul><li>ستوون: ناڤ، کورس، نمرە، دەرئەنجام</li><li><bdi>colspan</bdi> بو پێکڤەکرنا خانەیان</li><li>ڕیزەکا بو کۆمەل گشتی</li><li>ستایلا خشتەیێ د CSS دا</li></ul><p>پێ <bdi>rowspan</bdi> دکەی ڕیزان پێکڤە گری.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Xesteya Nmreyan</title>\n  <style>\n    body { font-family: Arial; background: #f0f4f8; }\n    table { width: 100%; max-width: 700px; margin: 30px auto; border-collapse: collapse; background: white; }\n    th, td { border: 1px solid #ccc; padding: 10px; text-align: center; }\n    th { background: #1565c0; color: white; }\n    tr:nth-child(even) { background: #f5f5f5; }\n    .serkeftî { color: green; font-weight: bold; }\n    .neketî { color: red; font-weight: bold; }\n  </style>\n</head>\n<body>\n  <table>\n    <tr><th>Nav</th><th>Kurs</th><th>Nimre</th><th>Encam</th></tr>\n    <tr><td>Rêzan</td><td>HTML</td><td>92</td><td class=\"serkeftî\">Serkeftî</td></tr>\n    <tr><td>Dilan</td><td>CSS</td><td>75</td><td class=\"serkeftî\">Serkeftî</td></tr>\n    <tr><td>Hejar</td><td>JavaScript</td><td>43</td><td class=\"neketî\">Neketiye</td></tr>\n    <tr><td colspan=\"3\"><b>Navînî</b></td><td><b>70</b></td></tr>\n  </table>\n</body>\n</html>"),

    lesson(33, $lv4so, $lv4ba, 'پرۆژە: ڕێستۆرانت - بەشی ١', 'پروژە: ڕێستۆرانت - بەش ١',
        '<p>پرۆژەیەکی گەورە: وێبپەڕەی ڕێستۆرانت. لەم بەشەدا سەرەتاکان:</p><ul><li><bdi>header</bdi> بە ناوی ڕێستۆرانت و ناڤیگەیشن</li><li>بەشی پێشوازی (hero) بە ناو و وەسف</li><li>دوگمەی داواکردن (Order)</li></ul><p>لە بەشی داهاتوودا مێنوو و فۆڕمی داواکاری دروست دەکەین.</p>',
        '<p>پروژەکا مەزن: وێبپەڕا ڕێستۆرانتێ. د ڤی بەشی دا سەرەتایێت:</p><ul><li><bdi>header</bdi> پێ ناڤێ ڕێستۆرانتێ و ناڤیگەیشن</li><li>بەشا پێشوازیێ (hero) پێ ناڤ و وەسف</li><li>دوگمەیا داواکرنێ (Order)</li></ul><p>د بەشێ داهاتێ دا مێنوو و فۆرما داواکاریێ دروست دکەین.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Restoranta Kurdi</title>\n  <style>\n    body { font-family: Arial; margin: 0; }\n    header { background: #4e342e; padding: 15px 30px; display: flex; justify-content: space-between; align-items: center; color: white; }\n    nav a { color: #ffcc80; margin-left: 15px; text-decoration: none; }\n    .hero { background: linear-gradient(45deg, #ff8f00, #e65100); color: white; text-align: center; padding: 60px 20px; }\n    .hero h1 { font-size: 42px; margin: 0; }\n    .hero button { background: #4e342e; color: white; border: none; padding: 12px 30px; border-radius: 25px; font-size: 16px; margin-top: 15px; }\n  </style>\n</head>\n<body>\n  <header>\n    <strong>Restoranta Kurdi</strong>\n    <nav><a href=\"#\">Mal</a><a href=\"#menu\">Menu</a><a href=\"#têkilî\">Têkilî</a></nav>\n  </header>\n  <div class=\"hero\">\n    <h1>Xwarinên Kurdî yên saxlem</h1>\n    <p>Kelpêş, dolme, biryan û bêtir... bi tehma malê</p>\n    <button>Niha Fermana xwe bide</button>\n  </div>\n</body>\n</html>"),

    lesson(34, $lv4so, $lv4ba, 'پرۆژە: ڕێستۆرانت - بەشی ٢', 'پروژە: ڕێستۆرانت - بەش ٢',
        '<p>بەشی دووەمی ڕێستۆرانت: مێنوو و فۆڕمی داواکردن:</p><ul><li>مێنوو بە خشتە: خۆراک، بەها</li><li>بەشەکان: خواردنی سەرەکی، خواردنی خێرا</li><li>فۆڕمی داواکاری بە select</li></ul><p>بە <bdi>&lt;option&gt;</bdi> دەتوانیت خۆراکەکان هەڵبژێریت.</p>',
        '<p>بەشێ دویێ ڕێستۆرانتێ: مێنوو و فۆرما داواکاریێ:</p><ul><li>مێنوو پێ خشتە: خوارن، بەها</li><li>بەش: خوارنێن سەرەکی، خوارنێن خێرا</li><li>فۆرما داواکاریێ پێ select</li></ul><p>پێ <bdi>&lt;option&gt;</bdi> دکەی خوارنان هەلبژیری.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Menu - Restoranta Kurdi</title>\n  <style>\n    body { font-family: Arial; margin: 0; background: #faf3e3; }\n    h1 { text-align: center; color: #4e342e; }\n    table { width: 90%; max-width: 600px; margin: 10px auto; border-collapse: collapse; background: white; }\n    th, td { border: 1px solid #d7ccc8; padding: 10px; }\n    th { background: #4e342e; color: white; }\n    form { max-width: 400px; margin: 20px auto; background: white; padding: 20px; border-radius: 8px; }\n    select, button { width: 100%; padding: 8px; margin-top: 8px; }\n  </style>\n</head>\n<body>\n  <h1>Menuya me</h1>\n  <table>\n    <tr><th>Xwarin</th><th>Biha</th></tr>\n    <tr><td>Kelpêş</td><td>12.000 IQD</td></tr>\n    <tr><td>Dolme</td><td>10.000 IQD</td></tr>\n    <tr><td>Biryan</td><td>15.000 IQD</td></tr>\n    <tr><td>Kubba</td><td>8.000 IQD</td></tr>\n  </table>\n  <form>\n    <label for=\"xwarin\">Xwarinê hilbijêre:</label>\n    <select id=\"xwarin\" name=\"xwarin\">\n      <option>Kelpêş</option>\n      <option>Dolme</option>\n      <option>Biryan</option>\n      <option>Kubba</option>\n    </select>\n    <button type=\"submit\">Fermanê bide</button>\n  </form>\n</body>\n</html>"),

    lesson(35, $lv4so, $lv4ba, 'پرۆژە: لاندینگ پەیج', 'پروژە: لاندینگ پەیج',
        '<p>پرۆژە: لاندینگ پەیج بۆ بەرهەمێک یان خزمەتگوزارییەک:</p><ul><li>بەشی پێشوازی بە ناونیشان و وەسف</li><li>بەشی تایبەتمەندییەکان (٣ کارت)</li><li>بەشی نرخەکان (3 بڕگە)</li><li>دوگمەی بانگهێشتی کردار (CTA)</li></ul><p>لاندینگ پەیج بۆ فرۆشتنی بەرهەمێک یان تۆمارکردنی بەکارهێنەر.</p>',
        '<p>پروژە: لاندینگ پەیج بو بەرهەمەکێ یا خزمەتگوزارییەکێ:</p><ul><li>بەشا پێشوازیێ پێ ناڤ و وەسف</li><li>بەشا تایبەتمەندییان (٣ کارت)</li><li>بەشا نرھا (3 بەش)</li><li>دوگمەیا بانگەشەیا کردارێ (CTA)</li></ul><p>لاندینگ پەیج بو فرۆتنا بەرهەمەکێ یا تۆمارکرنا بکارهێنەران.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Kursên Webê - Landing</title>\n  <style>\n    body { font-family: Arial; margin: 0; text-align: center; }\n    .hero { background: linear-gradient(135deg, #7c4dff, #536dfe); color: white; padding: 70px 20px; }\n    .hero h1 { font-size: 40px; }\n    .hero button { background: white; color: #536dfe; border: none; padding: 12px 30px; border-radius: 25px; font-size: 16px; }\n    .features { display: flex; flex-wrap: wrap; gap: 20px; justify-content: center; padding: 40px 20px; }\n    .card { border: 1px solid #ddd; border-radius: 10px; padding: 20px; width: 220px; }\n    .card h3 { color: #536dfe; }\n    .pricing { display: flex; gap: 20px; justify-content: center; padding: 30px 20px 60px; }\n    .plan { border: 2px solid #536dfe; border-radius: 10px; padding: 20px; width: 180px; }\n    .plan.premium { background: #536dfe; color: white; }\n  </style>\n</head>\n<body>\n  <div class=\"hero\">\n    <h1>Kursên Webê yên Kurdî</h1>\n    <p>HTML, CSS, JavaScript bi zimanê dayîkê</p>\n    <button>Niha dest pê bike</button>\n  </div>\n  <div class=\"features\">\n    <div class=\"card\"><h3>40 Ders</h3><p>Bi rêveçûna hêsan û projeyan</p></div>\n    <div class=\"card\"><h3>Bi Kurdî</h3><p>Her du zaravayên Kurdî</p></div>\n    <div class=\"card\"><h3>Praktîk</h3><p>Kodkirina rast di browserê de</p></div>\n  </div>\n  <div class=\"pricing\">\n    <div class=\"plan\"><h3>Belaş</h3><p>10 ders</p><p>0$</p></div>\n    <div class=\"plan premium\"><h3>Premium</h3><p>Hemû kurs</p><p>10$/meh</p></div>\n  </div>\n</body>\n</html>"),

    lesson(36, $lv4so, $lv4ba, 'پرۆژە: پەڕەی هەواڵ', 'پروژە: رووپەڵا نڤیساری',
        '<p>پرۆژە: پەڕەی هەواڵ. پێکهاتەکان:</p><ul><li>ناوەڕۆک: بابەتی سەرەکی (featured)</li><li>لیستی بابەتەکانی تر</li><li>بەشی <bdi>&lt;aside&gt;</bdi> بۆ هەواڵە بەناوبانگەکان</li><li>بەروار و کۆمێنت</li></ul><p><bdi>article</bdi> بۆ هەر هەواڵێک و <bdi>time</bdi> بۆ بەروار بەکاربهێنە.</p>',
        '<p>پروژە: رووپەڵا نڤیساری. پێکهاتە:</p><ul><li>ناڤەرۆک: بابەتێ سەرەکی (featured)</li><li>لیستا بابەتێن دی</li><li>بەشا <bdi>&lt;aside&gt;</bdi> بو نڤیسارێن بەناڤ</li><li>دیرۆک و کۆمێنت</li></ul><p><bdi>article</bdi> بو هەر نڤیسارەکێ و <bdi>time</bdi> بو دیرۆکێ بکاربینی.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Nûçe</title>\n  <style>\n    body { font-family: Arial; margin: 0; background: #f5f5f5; }\n    header { background: #b71c1c; color: white; padding: 15px 30px; }\n    .layout { display: grid; grid-template-columns: 2fr 1fr; gap: 20px; max-width: 1000px; margin: 20px auto; padding: 0 15px; }\n    .featured { background: white; border-radius: 8px; padding: 20px; }\n    .featured img { width: 100%; border-radius: 6px; }\n    article { background: white; border-radius: 8px; padding: 15px; margin-bottom: 15px; }\n    aside { background: #fff3e0; border-radius: 8px; padding: 15px; }\n    time { color: #999; font-size: 13px; }\n  </style>\n</head>\n<body>\n  <header><h1>Nûçeyên Kurdistanê</h1></header>\n  <div class=\"layout\">\n    <main>\n      <section class=\"featured\">\n        <img src=\"https://picsum.photos/600/300\" alt=\"Nûçeya sereke\">\n        <h2>Nûçeya sereke ya rojê</h2>\n        <time datetime=\"2026-07-31\">31 Tîrmeh 2026</time>\n        <p>Naveroka nûçeya sereke...</p>\n      </section>\n      <h3>Nûçeyên din</h3>\n      <article><h4>Sernavê nûçeyê 1</h4><time datetime=\"2026-07-30\">30 Tîrmeh 2026</time><p>Kurtenivîs...</p></article>\n      <article><h4>Sernavê nûçeyê 2</h4><time datetime=\"2026-07-29\">29 Tîrmeh 2026</time><p>Kurtenivîs...</p></article>\n    </main>\n    <aside>\n      <h3>Herî zêde tê xwendin</h3>\n      <ol>\n        <li>Nûçeya 1</li>\n        <li>Nûçeya 2</li>\n        <li>Nûçeya 3</li>\n      </ol>\n    </aside>\n  </div>\n</body>\n</html>"),

    lesson(37, $lv4so, $lv4ba, 'پرۆژە: پۆرتەفۆلیۆ', 'پروژە: پۆرتەفۆلیۆ',
        '<p>پرۆژە: پۆرتەفۆلیۆی کارەکانت. تێیدا دەبێت:</p><ul><li>بەشی پێشوازی کورتانە</li><li>تۆڕی grid بۆ پرۆژەکان</li><li>هەر کارت: وێنە، ناو، وەسف، لینک</li><li>بەشی پەیوەندیکردن</li></ul><p>پۆرتەفۆلیۆ باشترین ڕێگەیە بۆ پیشاندانی تواناکانت بە داھاتوویی.</p>',
        '<p>پروژە: پۆرتەفۆلیۆی کارێن تە. د ناڤ دا دڤێت:</p><ul><li>بەشا پێشوازیێ کورت</li><li>تۆڕا grid بو پروژەیان</li><li>هەر کارت: وێنە، ناڤ، وەسف، گرێدان</li><li>بەشا پەیوەندیێ</li></ul><p>پۆرتەفۆلیۆ ڕێگەیا باشترینە بو نیشاندانا توانایێن تە ب ئەردێکێ داهاتێ.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Portfoliyoya Min</title>\n  <style>\n    body { font-family: Arial; margin: 0; background: #f5f5f5; text-align: center; }\n    header { background: #212121; color: white; padding: 40px; }\n    .works { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; max-width: 900px; margin: 30px auto; padding: 0 15px; }\n    .work { background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 8px #ddd; }\n    .work img { width: 100%; height: 150px; object-fit: cover; }\n    .work h3 { margin: 12px; }\n    .work p { color: #666; margin: 0 12px 12px; }\n    footer { background: #212121; color: #bbb; padding: 15px; }\n  </style>\n</head>\n<body>\n  <header>\n    <h1>Rêzan - Web Developer</h1>\n    <p>Karên min ên herî dawî</p>\n  </header>\n  <div class=\"works\">\n    <div class=\"work\"><img src=\"https://picsum.photos/400/250?1\" alt=\"Projeya 1\"><h3>Malpera Restorantê</h3><p>HTML + CSS</p></div>\n    <div class=\"work\"><img src=\"https://picsum.photos/400/250?2\" alt=\"Projeya 2\"><h3>Blog</h3><p>HTML + CSS</p></div>\n    <div class=\"work\"><img src=\"https://picsum.photos/400/250?3\" alt=\"Projeya 3\"><h3>Landing Page</h3><p>HTML + CSS</p></div>\n  </div>\n  <footer>\n    <p>© 2026 Rêzan - <a href=\"mailto:rezan@example.com\">rezan@example.com</a></p>\n  </footer>\n</body>\n</html>"),

    lesson(38, $lv4so, $lv4ba, 'پرۆژە: وێبپەڕەی فێرکاری - بەشی ١', 'پروژە: وێبپەڕەکا فێرکاریێ - بەش ١',
        '<p>پرۆژە: وێبپەڕەی فێرکاری (وەک فێرگە). بەشی یەکەم:</p><ul><li>ناڤیگەیشنی سەرەوە بە لینکەکان</li><li>بەشی پێشوازی بە ناونیشان</li><li>کارتی زمانەکانی فێرکاری</li></ul><p>هەر کارتێک: وێنە، ناوی زمان، ژمارەی دەرسەکان، دوگمەی دەستپێکردن.</p>',
        '<p>پروژە: وێبپەڕەکا فێرکاریێ (وەک فێرگە). بەشێ یەکێ:</p><ul><li>ناڤیگەیشنا سەرەوێ پێ گرێدانان</li><li>بەشا پێشوازیێ پێ ناڤ</li><li>کارتێن زمانێن فێرکاریێ</li></ul><p>هەر کارتەک: وێنە، ناڤێ زمانێ، ژمارا دەرسان، دوگمەیا دستپێکرنێ.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Ferga - Platforma Fêrbûnê</title>\n  <style>\n    body { font-family: Arial; margin: 0; background: #f4f6f8; }\n    nav { background: #283593; padding: 15px 30px; color: white; display: flex; justify-content: space-between; }\n    nav a { color: white; margin-left: 15px; text-decoration: none; }\n    .hero { background: linear-gradient(120deg, #283593, #5c6bc0); color: white; text-align: center; padding: 60px 20px; }\n    .courses { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 20px; max-width: 950px; margin: 30px auto; padding: 0 15px; }\n    .course { background: white; border-radius: 10px; padding: 20px; text-align: center; box-shadow: 0 2px 8px #ddd; }\n    .course img { width: 70px; }\n    .course button { background: #283593; color: white; border: none; padding: 8px 20px; border-radius: 20px; }\n  </style>\n</head>\n<body>\n  <nav><strong>Ferga</strong><span><a href=\"#\">Mal</a><a href=\"#courses\">Kurs</a><a href=\"#\">Têkilî</a></span></nav>\n  <div class=\"hero\">\n    <h1>Kodkirinê bi Kurdî fêr bibe</h1>\n    <p>Kursên berfireh: Python, C++, HTML û CSS</p>\n  </div>\n  <div class=\"courses\" id=\"courses\">\n    <div class=\"course\"><img src=\"https://i.ibb.co/N6H7xFrx/python.jpg\" alt=\"Python\"><h3>Python</h3><p>40 ders</p><button>Dest pê bike</button></div>\n    <div class=\"course\"><img src=\"https://i.ibb.co/SwG1sTT7/cpp-logo.png\" alt=\"C++\"><h3>C++</h3><p>40 ders</p><button>Dest pê bike</button></div>\n    <div class=\"course\"><img src=\"https://i.ibb.co/TxzTB3pV/html5.png\" alt=\"HTML\"><h3>HTML</h3><p>40 ders</p><button>Dest pê bike</button></div>\n    <div class=\"course\"><img src=\"https://i.ibb.co/LDXg09TC/css3.png\" alt=\"CSS\"><h3>CSS</h3><p>40 ders</p><button>Dest pê bike</button></div>\n  </div>\n</body>\n</html>"),

    lesson(39, $lv4so, $lv4ba, 'پرۆژە: وێبپەڕەی فێرکاری - بەشی ٢', 'پروژە: وێبپەڕەکا فێرکاریێ - بەش ٢',
        '<p>بەشی دووەمی وێبپەڕەی فێرکاری:</p><ul><li>پەڕەی کۆرسی یەکەم (Python)</li><li>لیستی دەرسەکان بە <bdi>&lt;ol&gt;</bdi></li><li>بەشی بەردەوامبوون (Progress)</li><li>ناوەڕۆک بە <bdi>&lt;article&gt;</bdi></li></ul><p>بەشەکانی <bdi>header</bdi>، <bdi>main</bdi>، <bdi>aside</bdi> بەکاربهێنە بۆ لایۆتی باش.</p>',
        '<p>بەشێ دویێ وێبپەڕا فێرکاریێ:</p><ul><li>رووپەڵا کورسا یەکێ (Python)</li><li>لیستا دەرسان پێ <bdi>&lt;ol&gt;</bdi></li><li>بەشا دۆمەینی (Progress)</li><li>ناڤەرۆک پێ <bdi>&lt;article&gt;</bdi></li></ul><p>بەشێن <bdi>header</bdi>، <bdi>main</bdi>، <bdi>aside</bdi> بو لایۆتەکا باش بکاربینی.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Kursa Python</title>\n  <style>\n    body { font-family: Arial; margin: 0; background: #f4f6f8; }\n    header { background: #37474f; color: white; padding: 20px 30px; }\n    .layout { display: grid; grid-template-columns: 1fr 2fr; gap: 20px; max-width: 1000px; margin: 20px auto; padding: 0 15px; }\n    aside { background: white; border-radius: 8px; padding: 15px; }\n    aside li { margin: 8px 0; }\n    article { background: white; border-radius: 8px; padding: 20px; }\n    .done { color: green; }\n    code { background: #263238; color: #aeea00; padding: 2px 6px; border-radius: 4px; }\n  </style>\n</head>\n<body>\n  <header><h1>Kursa Python</h1></header>\n  <div class=\"layout\">\n    <aside>\n      <h3>Ders</h3>\n      <ol>\n        <li class=\"done\">Destpêk</li>\n        <li class=\"done\">Guvastin</li>\n        <li>Merc</li>\n        <li>Loops</li>\n      </ol>\n    </aside>\n    <main>\n      <article>\n        <h2>Ders 3: Merc</h2>\n        <p>Bi <code>if</code> û <code>else</code> biryar bidin.</p>\n        <pre>if n &gt; 0:\n    print(\"Pozîtîv\")\nelse:\n    print(\"Negatîv\")</pre>\n        <a href=\"#\">Dersa paşê</a>\n      </article>\n    </main>\n  </div>\n</body>\n</html>"),

    lesson(40, $lv4so, $lv4ba, 'پرۆژە: وێبپەڕەی تەواو', 'پروژە: وێبپەڕەکا تەمام',
        '<p>پرۆژەی کۆتایی: وێبپەڕەیەکی تەواو کە هەموو ئەو شتانەی کە فێربوویت تێدا بەکاربهێنیت:</p><ul><li>ناڤیگەیشنی سەرەوە</li><li>بەشی پێشوازی و چەند بەشێک</li><li>فۆڕم و خشتە</li><li>گالەری وێنە</li><li>دواوە (footer)</li></ul><p>بابەتی خۆت هەڵبژێرە: ڕێستۆرانت، کۆمپانیا، پۆرتەفۆلیۆ یان هەر شتێکی تر. ئەم پڕۆژەیە بۆ دەستخۆشی هەموو بەشەکانی HTML بەکاربهێنە. پیری! فێرگەی ڕاستەقینە بەم شێوەیە دروست دەکرێت.</p>',
        '<p>پروژەیا دویاهین: وێبپەڕەکا تەمام کو هەمی ئەو تیشتنان کو فێر بوی د ناڤ دا بکاربینی:</p><ul><li>ناڤیگەیشنا سەرەوێ</li><li>بەشا پێشوازیێ و چەند بەش</li><li>فۆرم و خشتە</li><li>گالەریا وێنەیان</li><li>دویاهیا (footer)</li></ul><p>بابەتێ خوە هەلبژیرە: ڕێستۆرانت، کۆمپانیا، پۆرتەفۆلیۆ یا هەر تیشتەکا دی. ئەڤ پروژەیێ بو دەستخۆشی هەمی بەشێن HTML بکاربینی. پیری! فێرگەیا راستی ب ڤی شێوەی دروست دبیت.</p>',
        "<!DOCTYPE html>\n<html lang=\"so\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>Malpera Te</title>\n  <style>\n    * { box-sizing: border-box; }\n    body { font-family: Arial; margin: 0; }\n    nav { background: #263238; color: white; padding: 15px 30px; display: flex; justify-content: space-between; }\n    nav a { color: #ffd54f; margin-left: 12px; text-decoration: none; }\n    .hero { text-align: center; background: linear-gradient(45deg, #00695c, #26a69a); color: white; padding: 70px 20px; }\n    section { max-width: 900px; margin: 30px auto; padding: 0 15px; }\n    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }\n    .card { background: #eceff1; border-radius: 8px; padding: 15px; }\n    footer { background: #263238; color: #bbb; text-align: center; padding: 15px; margin-top: 40px; }\n  </style>\n</head>\n<body>\n  <nav><strong>Malpera Min</strong><span><a href=\"#about\">Der barê</a><a href=\"#works\">Kar</a><a href=\"#contact\">Têkilî</a></span></nav>\n  <div class=\"hero\"><h1>Bi xêr hatî</h1><p>Ev malper ji hemû dersên HTML hat çêkirin</p></div>\n  <section id=\"about\"><h2>Der barê</h2><p>Kurtenivîsa malpera te...</p></section>\n  <section id=\"works\">\n    <h2>Karên me</h2>\n    <div class=\"grid\">\n      <div class=\"card\"><h3>Proje 1</h3><p>Wesf</p></div>\n      <div class=\"card\"><h3>Proje 2</h3><p>Wesf</p></div>\n      <div class=\"card\"><h3>Proje 3</h3><p>Wesf</p></div>\n    </div>\n  </section>\n  <section id=\"contact\">\n    <h2>Têkilî</h2>\n    <form>\n      <label>Nav: <input type=\"text\" name=\"nav\" required></label><br><br>\n      <label>E-mail: <input type=\"email\" name=\"email\" required></label><br><br>\n      <button type=\"submit\">Bisîne</button>\n    </form>\n  </section>\n  <footer><p>© 2026 - Hemû maf parastî ne</p></footer>\n</body>\n</html>"),
];

foreach ($lessons as $lesson) {
    $lesson['langId'] = $langId;
    $res = fbPost($firebaseUrl . 'ferga_lessons.json', $lesson);
    $d = json_decode($res, true);
    if (isset($d['name'])) {
        echo "Lesson added: {$lesson['title_so']} -> {$d['name']}\n";
    } else {
        echo "ERROR adding lesson {$lesson['title_so']}: $res\n";
    }
}

echo "\nDone! HTML lessons 21-40 added.\n";
