#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
B='/home/donk/kurd-ai-platform'
F='https://ai-platform-adb1b-default-rtdb.firebaseio.com/'
def pv(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '['+','.join(pv(i) for i in v)+']'
    return "'"+str(v).replace('\\','\\\\').replace("'","\\'")+  "'"
def run(fname,lang,lid,LL):
    L=['<?php',f"$u='{F}';$t=trim(file_get_contents('/tmp/opencode/fb_token.txt'));$lid='{lid}';",
       "function fp($url,$d){global $t;$c=curl_init($url);curl_setopt($c,CURLOPT_RETURNTRANSFER,true);curl_setopt($c,CURLOPT_POST,true);curl_setopt($c,CURLOPT_POSTFIELDS,json_encode($d));curl_setopt($c,CURLOPT_HTTPHEADER,['Authorization: Bearer '.$t,'Content-Type: application/json']);$r=curl_exec($c);curl_close($c);return $r;}",
       "function fpa($url,$d){global $t;$c=curl_init($url);curl_setopt($c,CURLOPT_RETURNTRANSFER,true);curl_setopt($c,CURLOPT_CUSTOMREQUEST,'PATCH');curl_setopt($c,CURLOPT_POSTFIELDS,json_encode($d));curl_setopt($c,CURLOPT_HTTPHEADER,['Authorization: Bearer '.$t,'Content-Type: application/json']);$r=curl_exec($c);curl_close($c);return $r;}",
       f"fpa($u.'ferga_languages/'.$lid.'.json',['locked'=>false]);echo \"{lang} OK\\n\";",
       '$lessons=[']
    for ls in LL:
        L.append('[')
        for k,v in ls.items(): L.append(f"  {pv(k)}=>{pv(v)},")
        L.append('],')
    L+=['];',"echo 'Adding '.count($lessons).' lessons...\\n';",
        "foreach($lessons as $l){$l['langId']=$lid;$r=fp($u.'ferga_lessons.json',$l);$d=json_decode($r,true);",
        "if(isset($d['name'])){echo 'OK '.$l['order'].\"\\n\";}else{echo 'ERR '.$r.\"\\n\";exit(1);}}",
        f"echo 'Done {lang}\\n';"]
    p=os.path.join(B,fname)
    with open(p,'w',encoding='utf-8') as f: f.write('\n'.join(L)+'\n')
    print(f'Wrote {p}')
s1so='ئاستی ١ - دەستپێکردن';s1ba='ئاستا ١ - دەستپێکرن'
s2so='ئاستی ٢ - مەرج و خولگە';s2ba='ئاستا ٢ - مەرج و گەڕخستن'
s3so='ئاستی ٣ - ئارا و دەق';s3ba='ئاستا ٣ - ئارا و نڤیسین'
s4so='ئاستی ٤ - فەنکشن و OOP';s4ba='ئاستا ٤ - فەنکشن و OOP'
s5so='ئاستی ٥ - وێب و پرۆژە';s5ba='ئاستا ٥ - وێب و پرۆژە'
php=[
{'order':1,'level_so':s1so,'level_ba':s1ba,'title_so':'چییە PHP؟','title_ba':'چ یە PHP؟',
 'content_so':'<p><strong>PHP</strong> زمانێکی server-side یە بۆ دروستکردنی ماڵپەڕی داینامیکی. لە WordPress، Laravel و زۆر فریمووەرک بەکاردێت.</p>',
 'content_ba':'<p><strong>PHP</strong> زمانەکەکا server-side یە بو دروستکرنا ماڵپەرێن داینامیکی. د WordPress، Laravel دا بکارتیت.</p>',
 'code':'<?php\necho "Silav Kurdistane!\\n";\necho "Xêrhatî bo PHP\\n";\necho "Sal: ".date("Y")."\\n";\n?>',
 'example_output':'Silav Kurdistane!\nXêrhatî bo PHP\nSal: 2026',
 'quiz_type':'choice','quiz_question_so':'PHP زمانێکی چییە؟','quiz_question_ba':'PHP زمانەکا چ یە؟',
 'quiz_options_so':['Server-side scripting','Desktop app','Mobile app','Game engine'],
 'quiz_options_ba':['Server-side scripting','Desktop app','Mobile app','Game engine'],'quiz_correct':0},

{'order':2,'level_so':s1so,'level_ba':s1ba,'title_so':'گۆڕاوەکان','title_ba':'گۆڕۆک',
 'content_so':'<p>لە PHP گۆڕاوەکان بە <code>$</code> دەستپێدەکەن. پێویست ناکات جۆر دیاری بکرێت — PHP خۆی دەزانێت:</p><pre>$nav = "Kurd"; $temen = 25; $nrx = 4.5; $drust = true;</pre>',
 'content_ba':'<p>د PHP دا گۆڕۆک پێ <code>$</code> دەست پێ دکەن. پێویست نییە چەشن دیاری بکی:</p><pre>$nav = "Kurd"; $temen = 25;</pre>',
 'code':'<?php\n$nav = "Kurd";\n$temen = 22;\n$bajar = "Hewler";\necho $nav . " ji " . $bajar . "\\n";\necho "Temen: " . $temen . "\\n";\necho "Cure: " . gettype($nav) . "\\n";\n?>',
 'example_output':'Kurd ji Hewler\nTemen: 22\nCure: string',
 'quiz_type':'choice',
 'quiz_question_so':'ئەمەی خوارەوە چی چاپ دەکات؟\n<?php $x=5; $y=3; echo $x+$y; ?>',
 'quiz_question_ba':'ئەڤ کودا خوارێ چ چاپ دکەت؟\n<?php $x=5; $y=3; echo $x+$y; ?>',
 'quiz_options_so':['8','53','$x+$y','هەڵە'],'quiz_options_ba':['8','53','$x+$y','خەلەت'],'quiz_correct':0},
{'order':3,'level_so':s1so,'level_ba':s1ba,'title_so':'ئۆپەراتۆرەکان','title_ba':'ئۆپەراتۆر',
 'content_so':'<p>PHP ئۆپەراتۆرە بیرکارییەکانی: <code>+</code>، <code>-</code>، <code>*</code>، <code>/</code>، <code>%</code>، <code>**</code>. بۆ دەق: <code>.</code> بەستن.</p>',
 'content_ba':'<p>PHP ئۆپەراتۆرێن ماتەماتیکی: <code>+</code>، <code>-</code>، <code>*</code>، <code>/</code>، <code>%</code>، <code>**</code>. بو نڤیسین: <code>.</code>.</p>',
 'code':'<?php\n$a=15; $b=4;\necho $a+$b."\\n";  // 19\necho $a-$b."\\n";  // 11\necho $a*$b."\\n";  // 60\necho $a/$b."\\n";  // 3.75\necho $a%$b."\\n";  // 3\necho $a**2."\\n";  // 225\n?>',
 'example_output':'19\n11\n60\n3.75\n3\n225',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\n<?php\n$nav = "Kurd";\necho $Name;\n?>',
 'practice_question_ba':'خەلەتا کودێ بدۆزە:\n<?php\n$nav = "Kurd";\necho $Name;\n?>',
 'expected_output_text':'Kurd','solution_code':'<?php\n$nav = "Kurd";\necho $nav; // case-sensitive\n?>','attempts_allowed':5},
{'order':4,'level_so':s1so,'level_ba':s1ba,'title_so':'دەقەکان (Strings)','title_ba':'نڤیسین (Strings)',
 'content_so':'<p>PHP فانکشنی دەقی زۆری هەیە: <code>strlen()</code>، <code>strtoupper()</code>، <code>strtolower()</code>، <code>substr()</code>، <code>str_replace()</code>.</p>',
 'content_ba':'<p>PHP فانکشنێن نڤیسینی زۆر: <code>strlen()</code>، <code>strtoupper()</code>، <code>substr()</code>.</p>',
 'code':'<?php\n$s = "Kurdistan";\necho strlen($s)."\\n";          // 9\necho strtoupper($s)."\\n";    // KURDISTAN\necho substr($s,0,4)."\\n";     // Kurd\necho str_replace("stan","",$s)."\\n"; // Kurdi\n?>',
 'example_output':'9\nKURDISTAN\nKurd\nKurdi',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە ناوی شارێک وەربگرێت و بە پیتی گەورە چاپی بکات.',
 'practice_question_ba':'بەرنامەکەک بنڤیسە کو ناڤا باژارەک وەربگریت و ب پیتێن مەزن چاپا وی بکەت.',
 'expected_output_text':'Bajar: HEWLER','solution_code':'<?php\n$b=readline("Bajar: ");\necho strtoupper($b)."\\n";\n?>','attempts_allowed':5},
{'order':5,'level_so':s1so,'level_ba':s1ba,'title_so':'مەرجی if/else','title_ba':'مەرجا if/else',
 'content_so':'<p>مەرجی <code>if/elseif/else</code> ڕێگەت دەدات بڕیار بدەیت:</p><pre>if ($nrx>=90) echo "Taqez";\nelseif ($nrx>=60) echo "Bas";\nelse echo "Nekefte";</pre>',
 'content_ba':'<p>مەرجا <code>if/elseif/else</code> ڕێگا دیتت دەت:</p><pre>if ($nrx>=90) echo "Taqez";\nelseif ($nrx>=60) echo "Bas";\nelse echo "Nekefte";</pre>',
 'code':'<?php\n$temen = 20;\nif ($temen >= 18) {\n    echo "Mezin buye\\n";\n} else {\n    echo "Picuk e\\n";\n}\n?>',
 'example_output':'Mezin buye',
 'quiz_type':'choice','quiz_question_so':'ئەگەر $temen=15 بێت، چی چاپ دەبێت؟','quiz_question_ba':'گەر $temen=15 بیت، چ چاپ دبیت؟',
 'quiz_options_so':['Picuk e','Mezin buye','هیچ','هەڵە'],'quiz_options_ba':['Picuk e','Mezin buye','هیچ','خەلەت'],'quiz_correct':0},
{'order':6,'level_so':s1so,'level_ba':s1ba,'title_so':'switch','title_ba':'switch',
 'content_so':'<p><code>switch</code> بۆ بەراوردکردن یەک بەها لەگەڵ چەند حالەت:</p><pre>switch($reng){\n  case "sor": echo "Sor"; break;\n  default: echo "Din";\n}</pre>',
 'content_ba':'<p><code>switch</code> بو بەراوردکرنا بەهایەک ل گەل چەند حالەتان:</p>',
 'code':'<?php\n$roj = "Sêşem";\nswitch($roj) {\n    case "Duşem": echo "Yekem roj\\n"; break;\n    case "Sêşem": echo "Duyem roj\\n"; break;\n    case "Înî": echo "Dawî heftê\\n"; break;\n    default: echo "Roja din\\n";\n}\n?>',
 'example_output':'Duyem roj',
 'quiz_type':'choice',
 'quiz_question_so':'ئەگەر $roj="Înî" بێت، چی چاپ دەبێت؟',
 'quiz_question_ba':'گەر $roj="Înî" بیت، چ چاپ دبیت؟',
 'quiz_options_so':['Dawî heftê','Yekem roj','Duyem roj','Roja din'],'quiz_options_ba':['Dawî heftê','Yekem roj','Duyem roj','Roja din'],'quiz_correct':0},

# L2: Control flow
{'order':7,'level_so':s2so,'level_ba':s2ba,'title_so':'خولگەی for','title_ba':'گەڕخستنا for',
 'content_so':'<p><code>for</code> بۆ دووبارەکردنەوە:</p><pre>for ($i=1;$i<=5;$i++) echo $i."\\n";</pre>',
 'content_ba':'<p><code>for</code> بو دووبارەکرن:</p><pre>for ($i=1;$i<=5;$i++) echo $i."\\n";</pre>',
 'code':'<?php\nfor ($i=1;$i<=5;$i++) echo "Jimare: $i\\n";\necho "Dawî bû\\n";\n?>',
 'example_output':'Jimare: 1\nJimare: 2\nJimare: 3\nJimare: 4\nJimare: 5\nDawî bû',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\n<?php\nfor ($i=1;$i<=3;$i--) echo $i."\\n";\n?>',
 'practice_question_ba':'خەلەتا کودێ بدۆزە:\n<?php\nfor ($i=1;$i<=3;$i--) echo $i."\\n";\n?>',
 'expected_output_text':'1\n2\n3','solution_code':'<?php\nfor ($i=1;$i<=3;$i++) echo $i."\\n"; // i++ ne i--\n?>','attempts_allowed':5},
{'order':8,'level_so':s2so,'level_ba':s2ba,'title_so':'while و do-while','title_ba':'while û do-while',
 'content_so':'<p><code>while</code> تا کاتێک مەرج راستە دەخولێت. <code>do-while</code> لانەکەمی یەک جار ئەجرا دەکات.</p>',
 'content_ba':'<p><code>while</code> هەتا کو مەرج راست دگەڕخیت. <code>do-while</code> لانەکەمی یەک جار ئیجرا دکەت.</p>',
 'code':'<?php\n$n=5;\nwhile ($n>0) { echo $n." "; $n--; }\necho "\\n";\n$j=0;\ndo { echo $j." "; $j++; } while ($j<3);\necho "\\n";\n?>',
 'example_output':'5 4 3 2 1 \n0 1 2 ',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە ژمارەی جۆتەکانی ٢ بۆ ١٠ بە while چاپ بکات.',
 'practice_question_ba':'بەرنامەکەک بنڤیسە کو ژمارێن جۆتی ٢ هەتا ١٠ پێ while چاپ بکەت.',
 'expected_output_text':'2\n4\n6\n8\n10','solution_code':'<?php\n$i=2;\nwhile($i<=10){echo $i."\\n";$i+=2;}\n?>','attempts_allowed':5},
{'order':9,'level_so':s2so,'level_ba':s2ba,'title_so':'foreach','title_ba':'foreach',
 'content_so':'<p><code>foreach</code> تایبەتە بۆ خولاندنی ئاراکان:</p><pre>$nav=["Azad","Baran"];\nforeach($nav as $n) echo $n."\\n";</pre>',
 'content_ba':'<p><code>foreach</code> تایبەتە بو خولاندنا ئاراکان:</p>',
 'code':'<?php\n$bajer=["Hewler","Silemani","Duhok"];\nforeach($bajer as $i=>$b) echo ($i+1).". $b\\n";\n?>',
 'example_output':'1. Hewler\n2. Silemani\n3. Duhok',
 'quiz_type':'choice','quiz_question_so':'foreach لە PHP بۆ چی بەکاردێت؟','quiz_question_ba':'foreach د PHP دا بو چی بکارتیت؟',
 'quiz_options_so':['خولاندنی ئاراکان','دروستکردنی فایل','پەیوەندی داتابەیس','کاری بیرکاری'],
 'quiz_options_ba':['خولاندنا ئاراکان','دروستکرنا فایل','Peywendî DB','Karê math'],'quiz_correct':0},
{'order':10,'level_so':s2so,'level_ba':s2ba,'title_so':'break و continue','title_ba':'break û continue',
 'content_so':'<p><code>break</code> خولگەکە دادەوەستێنێت. <code>continue</code> گەڕانی ئێستا تێپەردەی دەکات.</p>',
 'content_ba':'<p><code>break</code> گەڕخستن دادەستنێت. <code>continue</code> گەڕانا ئێستا تێپەڕ دکەت.</p>',
 'code':'<?php\nfor($i=1;$i<=10;$i++){\n    if($i==7) break;\n    if($i%2==0) continue;\n    echo $i." ";\n}\necho "\\n";\n?>',
 'example_output':'1 3 5 ',
 'quiz_type':'choice',
 'quiz_question_so':'ئەمەی خوارەوە چی چاپ دەکات؟\n<?php\nfor($i=1;$i<=5;$i++){\n  if($i==3) continue;\n  echo $i." ";\n}\n?>',
 'quiz_question_ba':'ئەڤ کودا خوارێ چ چاپ دکەت؟\n<?php\nfor($i=1;$i<=5;$i++){\n  if($i==3) continue;\n  echo $i." ";\n}\n?>',
 'quiz_options_so':['1 2 4 5 ','1 2 3 4 5 ','1 2 ','هەڵە'],'quiz_options_ba':['1 2 4 5 ','1 2 3 4 5 ','1 2 ','خەلەت'],'quiz_correct':0},
{'order':11,'level_so':s2so,'level_ba':s2ba,'title_so':'خولگەی تێکەڵ','title_ba':'گەڕخستنا تێکەل',
 'content_so':'<p>خولگەی تێکەڵ: خولگەیەک لە ناو خولگەیەکدا. بۆ جەدەوەل و نموونەکان بەکاردێت.</p>',
 'content_ba':'<p>گەڕخستنا تێکەل: گەڕخستنەک لە ناو گەڕخستنەکا دی. بو جەدەوەلان بکارتیت.</p>',
 'code':'<?php\nfor($i=1;$i<=3;$i++){\n    for($j=1;$j<=3;$j++) printf("%4d",$i*$j);\n    echo "\\n";\n}\n?>',
 'example_output':'   1   2   3\n   2   4   6\n   3   6   9',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\n<?php\nfor($i=1;$i<=3;$i++)\n    for($j=1;$j<=3;$j++)\n    echo $j." ";\n    echo "\\n";\n?>',
 'practice_question_ba':'خەلەتا کودێ بدۆزە:\n<?php\nfor($i=1;$i<=3;$i++)\n    for($j=1;$j<=3;$j++)\n    echo $j." ";\n    echo "\\n";\n?>',
 'expected_output_text':'1 2 3 \n1 2 3 \n1 2 3 ','solution_code':'<?php\nfor($i=1;$i<=3;$i++){\n    for($j=1;$j<=3;$j++) echo $j." ";\n    echo "\\n";\n}\n?>','attempts_allowed':5},
{'order':12,'level_so':s2so,'level_ba':s2ba,'title_so':'مەرجی Ternary','title_ba':'Mêrca Ternary',
 'content_so':'<p>Ternary شێوەی کورتی if/else: <code>$encam = $mêrj ? $erê : $na;</code></p><pre>$temen=20;\necho $temen>=18 ? "Mezin" : "Picuk";</pre>',
 'content_ba':'<p>Ternary şêwazê kurt yê if/else: <code>$encam = $mêrj ? $erê : $na;</code></p>',
 'code':'<?php\n$nrx = 85;\n$asta = $nrx>=90 ? "Taqez" : ($nrx>=60 ? "Bas" : "Nekefte");\necho $asta."\\n";\n$reng="kesk";\necho ($reng=="kesk") ? "Rengê xweza\\n" : "Rengekî din\\n";\n?>',
 'example_output':'Bas\nRengê xweza',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە ژمارەیەک وەربگرێت و بە ternary بەراوردبکات: ئەگەر گەورەتر لە ١٠ بێت "Mezin" بەڵام نەوەک "Biçûk" چاپ بکات.',
 'practice_question_ba':'بەرنامەکەک بنڤیسە کو ژمارەکا وەربگریت و ب ternary: گەر مەزنتر ژ ١٠ بیت "Mezin" نەوەک "Biçûk" چاپ بکەت.',
 'expected_output_text':'Jimare: 15\nMezin','solution_code':'<?php\n$j=(int)readline("Jimare: ");\necho ($j>10?"Mezin":"Bicuk")."\\n";\n?>','attempts_allowed':5},

# L3: Arrays & strings
{'order':13,'level_so':s3so,'level_ba':s3ba,'title_so':'ئارای ئیندێکس','title_ba':'ئارایا Indeks',
 'content_so':'<p>ئارای لە PHP کۆمەڵێک بەهای لە ژێر یەک ناودا:</p><pre>$nav=["Azad","Baran","Ciya"];\necho $nav[0]; // Azad\necho count($nav); // 3\n$nav[]="Dara"; // زیادکردن</pre>',
 'content_ba':'<p>ئارا د PHP دا کۆمەکێک بەهایان ژێر یەک ناڤ:</p><pre>$nav=["Azad","Baran"];\necho $nav[0]; // Azad\necho count($nav); // 2</pre>',
 'code':'<?php\n$nrx=[85,92,78,95,67];\nsort($nrx);\nforeach($nrx as $n) echo $n." ";\necho "\\nMax: ".max($nrx)."\\n";\necho "Min: ".min($nrx)."\\n";\n?>',
 'example_output':'67 78 85 92 95 \nMax: 95\nMin: 67',
 'quiz_type':'choice','quiz_question_so':'ئەمەی خوارەوە چی چاپ دەکات؟\n$a=[3,1,4,1,5];\necho count($a);','quiz_question_ba':'ئەڤ کودا خوارێ چ چاپ دکەت؟\n$a=[3,1,4,1,5];\necho count($a);',
 'quiz_options_so':['5','4','14','هەڵە'],'quiz_options_ba':['5','4','14','خەلەت'],'quiz_correct':0},
{'order':14,'level_so':s3so,'level_ba':s3ba,'title_so':'ئارای هاوشێوە','title_ba':'ئارایا Hevseng',
 'content_so':'<p>ئارای هاوشێوە (associative) کلیل و بەهایەک هەیە:</p><pre>$kes=["nav"=>"Azad","temen"=>25];\necho $kes["nav"]; // Azad</pre>',
 'content_ba':'<p>ئارایا hevşêweyê kilîl û behe heye:</p><pre>$kes=["nav"=>"Azad","temen"=>25];\necho $kes["nav"]; // Azad</pre>',
 'code':'<?php\n$xwendekar=["nav"=>"Baran","nrx"=>88,"bajer"=>"Hewler"];\nforeach($xwendekar as $k=>$v) echo "$k: $v\\n";\n?>',
 'example_output':'nav: Baran\nnrx: 88\nbajer: Hewler',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\n<?php\n$a=["nav"=>"Kurd"];\necho $a[nav];\n?>',
 'practice_question_ba':'خەلەتا کودێ بدۆزە:\n<?php\n$a=["nav"=>"Kurd"];\necho $a[nav];\n?>',
 'expected_output_text':'Kurd','solution_code':'<?php\n$a=["nav"=>"Kurd"];\necho $a["nav"]; // دڤێت quotes هەبیت\n?>','attempts_allowed':5},
{'order':15,'level_so':s3so,'level_ba':s3ba,'title_so':'فانکشنی ئارا','title_ba':'Fanksiyonên Araya',
 'content_so':'<p>PHP فانکشنی ئارایی زۆری هەیە: <code>array_push()</code>، <code>array_pop()</code>، <code>array_search()</code>، <code>in_array()</code>، <code>array_merge()</code>.</p>',
 'content_ba':'<p>PHP fanksiyonên araya: <code>array_push()</code>، <code>array_pop()</code>، <code>in_array()</code>.</p>',
 'code':'<?php\n$bajer=["Hewler","Silemani"];\narray_push($bajer,"Duhok","Zaxo");\necho implode(", ",$bajer)."\\n";\necho in_array("Duhok",$bajer)?"Heye\\n":"Nîne\\n";\n$jimare=[5,2,8,1];\nrsort($jimare);\nprint_r($jimare);\n?>',
 'example_output':'Hewler, Silemani, Duhok, Zaxo\nHeye\nArray\n(\n    [0] => 8\n    [1] => 5\n    [2] => 2\n    [3] => 1\n)',
 'quiz_type':'choice','quiz_question_so':'<code>in_array("x",$a)</code> چی دەگەڕێنێتەوە ئەگەر "x" نەبێت؟','quiz_question_ba':'<code>in_array("x",$a)</code> چ دگەڕینێتەوە گەر "x" نەبیت؟',
 'quiz_options_so':['false','null','0','هەڵە'],'quiz_options_ba':['false','null','0','خەلەت'],'quiz_correct':0},
{'order':16,'level_so':s3so,'level_ba':s3ba,'title_so':'فانکشنی دەق','title_ba':'Fanksiyonên Nivîsînê',
 'content_so':'<p>فانکشنی دەقی گرنگ: <code>trim()</code>، <code>explode()</code>، <code>implode()</code>، <code>str_pad()</code>، <code>number_format()</code>، <code>sprintf()</code>.</p>',
 'content_ba':'<p>Fanksiyonên girîng: <code>trim()</code>، <code>explode()</code>، <code>implode()</code>.</p>',
 'code':'<?php\n$navên="Azad,Baran,Ciya";\n$lîste=explode(",",$navên);\nforeach($lîste as $n) echo "- ".trim($n)."\\n";\necho implode(" | ",$lîste)."\\n";\n$nrx=1234567.89;\necho number_format($nrx,2,".","،")."\\n";\n?>',
 'example_output':'- Azad\n- Baran\n- Ciya\nAzad | Baran | Ciya\n1،234،567.89',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە ریزبەندێک لەگەڵ explode جیا بکات بە فاصڵە.',
 'practice_question_ba':'بەرنامەکەک بنڤیسە کو rêzeke pê explode ji "," bike.',
 'expected_output_text':'Hewler\nSimlemani\nDuhok','solution_code':'<?php\n$s="Hewler,Simlemani,Duhok";\n$a=explode(",",$s);\nforeach($a as $b) echo $b."\\n";\n?>','attempts_allowed':5},
{'order':17,'level_so':s3so,'level_ba':s3ba,'title_so':'Date و Time','title_ba':'Date û Time',
 'content_so':'<p>PHP <code>date()</code> فانکشنی بۆ کاتژمێر و ڕێکەوت:</p><pre>echo date("Y-m-d");     // 2026-08-06\necho date("H:i:s");     // 14:30:00\necho time();            // Unix timestamp</pre>',
 'content_ba':'<p>PHP <code>date()</code> fanksiyonê bO dema û rojê:</p><pre>echo date("Y-m-d");\necho date("H:i:s");\necho time();</pre>',
 'code':'<?php\necho "Sal: ".date("Y")."\\n";\necho "Mang: ".date("m")."\\n";\necho "Roj: ".date("d")."\\n";\n$zeman=mktime(0,0,0,8,6,2026);\necho date("d/m/Y",$zeman)."\\n";\n?>',
 'example_output':'Sal: 2026\nMang: 08\nRoj: 06\n06/08/2026',
 'quiz_type':'choice','quiz_question_so':'date("Y") چی دەگەڕێنێتەوە؟','quiz_question_ba':'date("Y") çi degerîne?',
 'quiz_options_so':['ساڵی ئێستا','مانگی ئێستا','ڕۆژی ئێستا','کاتژمێر'],'quiz_options_ba':['Sala niha','Meha niha','Roja niha','Saet'],'quiz_correct':0},
{'order':18,'level_so':s3so,'level_ba':s3ba,'title_so':'Math Functions','title_ba':'Fanksiyonên Math',
 'content_so':'<p>PHP فانکشنی ماتماتیکی زۆری هەیە: <code>abs()</code>، <code>ceil()</code>، <code>floor()</code>، <code>round()</code>، <code>sqrt()</code>، <code>pow()</code>، <code>rand()</code>.</p>',
 'content_ba':'<p>PHP fanksiyonên matematîkî: <code>abs()</code>، <code>ceil()</code>، <code>sqrt()</code>، <code>rand()</code>.</p>',
 'code':'<?php\necho abs(-15)."\\n";      // 15\necho ceil(4.2)."\\n";     // 5\necho floor(4.9)."\\n";    // 4\necho round(4.567,2)."\\n"; // 4.57\necho sqrt(144)."\\n";     // 12\necho pow(2,10)."\\n";     // 1024\n?>',
 'example_output':'15\n5\n4\n4.57\n12\n1024',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\n<?php\necho squareroot(16);\n?>',
 'practice_question_ba':'خەلەتا کودێ بدۆزە:\n<?php\necho squareroot(16);\n?>',
 'expected_output_text':'4','solution_code':'<?php\necho sqrt(16); // sqrt() ne squareroot()\n?>','attempts_allowed':5},

# L4: Functions & OOP
{'order':19,'level_so':s4so,'level_ba':s4ba,'title_so':'فەنکشن','title_ba':'Fanksiyonên',
 'content_so':'<p>فەنکشن بەشێکی کۆدی دووبارە بەکارهاتنییە:</p><pre>function kot($a,$b) { return $a+$b; }\necho kot(3,5); // 8</pre>',
 'content_ba':'<p>Fanksiyoneke beşek kode ku dîsa tê bikaranîn:</p><pre>function kot($a,$b){return $a+$b;}\necho kot(3,5); // 8</pre>',
 'code':'<?php\nfunction pakkirdin($nav){\n    return trim(strtolower($nav));\n}\nfunction pezkirdin($n,$p=2){\n    return round($n,$p);\n}\necho pakkirdin("  KURD  ")."\\n"; // kurd\necho pezkirdin(3.14159)."\\n";  // 3.14\n?>',
 'example_output':'kurd\n3.14',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\n<?php\nfunction selam $nav) {\n    echo "Silav $nav!\\n";\n}\nselam("Kurd");\n?>',
 'practice_question_ba':'خەلەتا کودێ بدۆزە:\n<?php\nfunction selam $nav) {\n    echo "Silav $nav!\\n";\n}\nselam("Kurd");\n?>',
 'expected_output_text':'Silav Kurd!','solution_code':'<?php\nfunction selam($nav) { // pêwîste "(" hebe\n    echo "Silav $nav!\\n";\n}\nselam("Kurd");\n?>','attempts_allowed':5},
{'order':20,'level_so':s4so,'level_ba':s4ba,'title_so':'Scope و Return','title_ba':'Scope û Return',
 'content_so':'<p>گۆڕاوە گلۆبالەکان لە ناو فەنکشن ناکرێن بەکاربهێنرێن بەبێ <code>global</code>:</p><pre>$x = 10;\nfunction test(){\n    global $x;\n    echo $x;\n}</pre>',
 'content_ba':'<p>Giyorvaokên global nakevin nav fanksiyonê bê <code>global</code>:</p>',
 'code':'<?php\n$jimare=100;\nfunction zedeke($n){\n    return $n * 2;\n}\nfunction global_test(){\n    global $jimare;\n    $jimare += 50;\n}\nglobal_test();\necho $jimare."\\n";    // 150\necho zedeke(7)."\\n";  // 14\n?>',
 'example_output':'150\n14',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە فەنکشنێکی recursive بنووسێت کە factorial بژمێرێت.',
 'practice_question_ba':'Bernameyeke binivîse ko fanksiyoneke recursive binivîse ko factorial bijmêre.',
 'expected_output_text':'5! = 120','solution_code':'<?php\nfunction factorial($n){\n    if($n<=1) return 1;\n    return $n * factorial($n-1);\n}\necho "5! = ".factorial(5)."\\n";\n?>','attempts_allowed':5},
{'order':21,'level_so':s4so,'level_ba':s4ba,'title_so':'کلاس و Object','title_ba':'Klas û Object',
 'content_so':'<p>کلاس شابلۆنی ئۆبجێکتێکە. بە <code>new</code> ئۆبجێکت دروست دەکرێت:</p><pre>class Mirov {\n    public $nav;\n    function danasîn() { echo $this->nav; }\n}</pre>',
 'content_ba':'<p>Klas şabloneke bO objekt. Bi <code>new</code> obekt tê çêkirin:</p>',
 'code':'<?php\nclass Xwendekar {\n    public $nav;\n    public $nrx;\n    function __construct($n,$s){\n        $this->nav=$n; $this->nrx=$s;\n    }\n    function danasîn(){\n        echo $this->nav.": ".$this->nrx."\\n";\n    }\n}\n$x=new Xwendekar("Azad",92);\n$x->danasîn();\necho $x->nav."\\n";\n?>',
 'example_output':'Azad: 92\nAzad',
 'quiz_type':'choice','quiz_question_so':'لە PHP $this چییە؟','quiz_question_ba':'Di PHP de $this çi ye?',
 'quiz_options_so':['ئاماژەی ئۆبجێکتی ئێستا','گۆڕاوی گلۆبال','فەنکشن','ئارا'],
 'quiz_options_ba':['Referansa obejkta niha','Giyorvaek global','Fanksiyoneke','Array'],'quiz_correct':0},
{'order':22,'level_so':s4so,'level_ba':s4ba,'title_so':'Inheritance','title_ba':'Inheritance',
 'content_so':'<p>Inheritance ڕێگەت دەدات کلاسێک تایبەتمەندی کلاسێکی تری وەربگرێت بە <code>extends</code>.</p>',
 'content_ba':'<p>Inheritance di PHP bi <code>extends</code>:</p>',
 'code':'<?php\nclass Heywên {\n    public $nav;\n    function __construct($n){ $this->nav=$n; }\n    function xwe(){ echo "Ez ".get_class($this)." im\\n"; }\n}\nclass Se extends Heywên {\n    function deng(){ echo $this->nav." dibêje: Haw!\\n"; }\n}\n$s=new Se("Zato");\n$s->xwe();\n$s->deng();\n?>',
 'example_output':'Ez Se im\nZato dibêje: Haw!',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\n<?php\nclass A { function test(){ echo "A\\n"; } }\nclass B implements A {}\n$b=new B();\n$b->test();\n?>',
 'practice_question_ba':'خەلەتا کودێ بدۆزە:\n<?php\nclass A { function test(){ echo "A\\n"; } }\nclass B implements A {}\n$b=new B();\n$b->test();\n?>',
 'expected_output_text':'A','solution_code':'<?php\nclass A { function test(){ echo "A\\n"; } }\nclass B extends A {} // extends ne implements bo klas\n$b=new B();\n$b->test();\n?>','attempts_allowed':5},
{'order':23,'level_so':s4so,'level_ba':s4ba,'title_so':'Interface و Abstract','title_ba':'Interface û Abstract',
 'content_so':'<p>Interface گڕێبەستی بەکلاسەکان دادەبەستێت. Abstract کلاسێکی نیوەکارکراوە.</p>',
 'content_ba':'<p>Interface girêbestê li klaşan datebeste. Abstract klaşeke nîwekarkrawiye.</p>',
 'code':'<?php\ninterface Şanoy {\n    public function şano();\n}\nclass Stranbêj implements Şanoy {\n    public $nav;\n    function __construct($n){ $this->nav=$n; }\n    public function şano(){\n        echo $this->nav." stran dixwîne\\n";\n    }\n}\n$s=new Stranbêj("Şivan");\n$s->şano();\n?>',
 'example_output':'Şivan stran dixwîne',
 'quiz_type':'choice','quiz_question_so':'Interface لە PHP بۆ چی بەکاردێت؟','quiz_question_ba':'Interface di PHP de bO çi tê bikaranîn?',
 'quiz_options_so':['دیاریکردنی گڕێبەست','وەرثەی کلاس','دروستکردنی ئۆبجێکت','خولاندنی ئارا'],
 'quiz_options_ba':['Diyarkirina girêbest','Mîrêya klas','Çêkirina obejkt','Xolandina araye'],'quiz_correct':0},
{'order':24,'level_so':s4so,'level_ba':s4ba,'title_so':'Exception Handling','title_ba':'Exception Handling',
 'content_so':'<p><code>try/catch/finally</code> بۆ کۆنترۆڵکردنی هەڵەکان:</p><pre>try { throw new Exception("Hêle"); }\ncatch(Exception $e){ echo $e->getMessage(); }\nfinally{ echo "Her tim"; }</pre>',
 'content_ba':'<p><code>try/catch/finally</code> bO kontrolkirina helekan:</p>',
 'code':'<?php\nfunction dabeşkirin($a,$b){\n    if($b===0) throw new Exception("Dabeşkirina bi sifir!");\n    return $a/$b;\n}\ntry {\n    echo dabeşkirin(10,2)."\\n";\n    echo dabeşkirin(10,0)."\\n";\n} catch(Exception $e) {\n    echo "Hêle: ".$e->getMessage()."\\n";\n} finally {\n    echo "Temam bû\\n";\n}\n?>',
 'example_output':'5\nHêle: Dabeşkirina bi sifir!\nTemam bû',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە هەڵەی ئارایی دەرجووی سنوور بگرێتەوە.',
 'practice_question_ba':'Bernameyeke binivîse ko helaya arrayek ji sinor derket bigire.',
 'expected_output_text':'Hêle: Index tune\nTemam bû','solution_code':'<?php\ntry{\n    $a=[1,2,3];\n    if(!isset($a[10])) throw new Exception("Index tune");\n} catch(Exception $e){\n    echo "Hêle: ".$e->getMessage()."\\n";\n} finally{\n    echo "Temam bû\\n";\n}\n?>','attempts_allowed':5},
# L5: Web & Project
{'order':25,'level_so':s5so,'level_ba':s5ba,'title_so':'GET و POST','title_ba':'GET û POST',
 'content_so':'<p>لە PHP <code>$_GET</code> و <code>$_POST</code> داخڵی فۆڕمی وێب وەردەگرن.</p><pre>// URL: ?nav=Kurd\necho $_GET["nav"]; // Kurd\n// فۆڕمی POST:\necho $_POST["email"];</pre>',
 'content_ba':'<p>Di PHP de <code>$_GET</code> û <code>$_POST</code> daneyên formê werdidgirin.</p>',
 'code':'<?php\n// Simulation ya form data\n$_POST["nav"]="Azad";\n$_POST["email"]="azad@kurd.ai";\nif(!empty($_POST["nav"])){\n    $nav=htmlspecialchars($_POST["nav"]);\n    echo "Silav, $nav!\\n";\n    echo "Email: ".$_POST["email"]."\\n";\n} else {\n    echo "Nav vala ye\\n";\n}\n?>',
 'example_output':'Silav, Azad!\nEmail: azad@kurd.ai',
 'quiz_type':'choice','quiz_question_so':'htmlspecialchars() بۆ چی بەکاردێت؟','quiz_question_ba':'htmlspecialchars() bO çi tê bikaranîn?',
 'quiz_options_so':['پارێزگاری لە XSS','ئینکۆدکردنی دەق','هەڵگرتنی فایل','پەیوەندی داتابەیس'],
 'quiz_options_ba':['Parêzgariya XSS','Enkodkirina nivîsê','Hilgirtina file','Peywendiya DB'],'quiz_correct':0},
{'order':26,'level_so':s5so,'level_ba':s5ba,'title_so':'فایل خوێندن و نووسین','title_ba':'File Xwendin û Nivîsîn',
 'content_so':'<p>PHP فانکشنی فایلی زۆری هەیە: <code>file_put_contents()</code>، <code>file_get_contents()</code>، <code>fopen()</code>.</p>',
 'content_ba':'<p>PHP fanksiyonên file: <code>file_put_contents()</code>، <code>file_get_contents()</code>.</p>',
 'code':'<?php\n$nav="/tmp/kurd_test.txt";\nfile_put_contents($nav,"Silav Kurdistan!\\nJava bax e\\n");\n$nav2=file_get_contents($nav);\necho $nav2;\n$rêz=file($nav);\necho "Jimare rêzan: ".count($rêz)."\\n";\nunlink($nav); // jêbirine\n?>',
 'example_output':'Silav Kurdistan!\nJava bax e\nJimare rêzan: 2',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە ژمارەی ریزەکانی فایلێک بژمێرێت.',
 'practice_question_ba':'Bernameyeke binivîse ko hejmara rêzan a fileke bijmêre.',
 'expected_output_text':'Rêz: 3','solution_code':'<?php\n$f="/tmp/t.txt";\nfile_put_contents($f,"r1\\nr2\\nr3\\n");\necho "Rêz: ".count(file($f))."\\n";\nunlink($f);\n?>','attempts_allowed':5},
{'order':27,'level_so':s5so,'level_ba':s5ba,'title_so':'Session','title_ba':'Session',
 'content_so':'<p>Session داتا لەنێوان داواکاریەکان هەلدەگرێت:</p><pre>session_start();\n$_SESSION["nav"]="Kurd";\n// لەسەر پەیجی دیکە:\necho $_SESSION["nav"]; // Kurd</pre>',
 'content_ba':'<p>Session daneyan di navbera daxwazîyan de dihêle:</p>',
 'code':'<?php\n// Simulation bê session_start() bo test\n$_SESSION=["nav"=>"Azad","rol"=>"Admin"];\necho "Nav: ".$_SESSION["nav"]."\\n";\necho "Rol: ".$_SESSION["rol"]."\\n";\nif(isset($_SESSION["nav"])) echo "Session heye\\n";\nunset($_SESSION["nav"]);\necho (isset($_SESSION["nav"]) ? "Heye" : "Tune")."\\n";\n?>',
 'example_output':'Nav: Azad\nRol: Admin\nSession heye\nTune',
 'quiz_type':'choice','quiz_question_so':'session_start() کەی دەبێت بانگ بکرێت؟','quiz_question_ba':'session_start() kengî divê were bangkirin?',
 'quiz_options_so':['پێش هەر output','دواتر هەر کاتێک','دواتر HTML','تەنها یەک جار'],
 'quiz_options_ba':['Beriya her çapkirinê','Piştî çapkirinê','Piştî HTML','Tenê carekê'],'quiz_correct':0},
{'order':28,'level_so':s5so,'level_ba':s5ba,'title_so':'پرۆژە: ماشێنی ژمارەکردن','title_ba':'Proje: Mêşîna Jimarê',
 'content_so':'<p>پرۆژەی یەکەم — ماشێنی ژمارەکردنی سادە:</p>',
 'content_ba':'<p>Proje ya yekem — mêşîna jimarêkirina sade:</p>',
 'code':'<?php\nfunction calculate($a,$op,$b){\n    switch($op){\n        case "+": return $a+$b;\n        case "-": return $a-$b;\n        case "*": return $a*$b;\n        case "/": return $b!=0 ? $a/$b : "Hêle: sifir";\n        default: return "Operator nenas";\n    }\n}\n$tests=[[10,"+",$5=5],[20,"-",8],[6,"*",7],[15,"/",3]];\nforeach($tests as $t)\n    echo $t[0]." ".$t[1]." ".$t[2]." = ".calculate($t[0],$t[1],$t[2])."\\n";\n?>',
 'example_output':'10 + 5 = 15\n20 - 8 = 12\n6 * 7 = 42\n15 / 3 = 5',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە ئارایەک لەگەڵ foreach ئۆپریشن بکات و ناوەندی هەمووی بژمێرێت.',
 'practice_question_ba':'Bernameyeke binivîse ko arreyeke pê foreach operasyon bike û navenda hemiyê bijmêre.',
 'expected_output_text':'Navend: 80','solution_code':'<?php\n$nrx=[75,80,90,70,85];\n$k=0;\nforeach($nrx as $n) $k+=$n;\necho "Navend: ".($k/count($nrx))."\\n";\n?>','attempts_allowed':5},
{'order':29,'level_so':s5so,'level_ba':s5ba,'title_so':'پرۆژە: ئەرشیفی بەرهەم','title_ba':'Proje: Erşîva Hilberê',
 'content_so':'<p>پرۆژەی دووەم — سیستەمی ئەرشیفی بەرهەمی فرۆشگا:</p>',
 'content_ba':'<p>Projeya duyem — sîstema erşîva hilberên dukênê:</p>',
 'code':'<?php\nclass Hilber {\n    public $nav, $nrx, $hejmar;\n    function __construct($n,$p,$h){ $this->nav=$n; $this->nrx=$p; $this->hejmar=$h; }\n    function giştî(){ return $this->nrx * $this->hejmar; }\n}\n$hilber=[new Hilber("Sêv",2.5,10),new Hilber("Tirî",5.0,6),new Hilber("Gûz",3.0,8)];\n$gişt=0;\nforeach($hilber as $h){\n    echo $h->nav.": ".$h->giştî()."\\n";\n    $gişt+=$h->giştî();\n}\necho "Giştî: $gişt\\n";\n?>',
 'example_output':'Sêv: 25\nTirî: 30\nGûz: 24\nGiştî: 79',
 'quiz_type':'choice','quiz_question_so':'OOP لە PHP چیان دەبێتە ئاسانتر؟','quiz_question_ba':'OOP di PHP de çi hêsantir dike?',
 'quiz_options_so':['ڕێکخستن و دووبارە بەکارهێنانی کۆد','خێراتر کردنی کۆد','کۆچ بردن بۆ داتابەیس','دروستکردنی UI'],
 'quiz_options_ba':['Rêxistin û dûbarebûna kodê','Bilez kirina kodê','Koçberdina DB','Çêkirina UI'],'quiz_correct':0},
{'order':30,'level_so':s5so,'level_ba':s5ba,'title_so':'کۆتایی کۆرس — پرۆژەی کۆتایی','title_ba':'Dawiya Kursê — Proje ya Dawî',
 'content_so':'<p>ئافەرین! گەیشتیتە کۆتایی کۆرسی PHP. ئەوەی فێربوویت: گۆڕاوەکان، دەق، ئارا، if/else، for/while/foreach، فەنکشن، OOP، Exception، فایل، Session.</p>',
 'content_ba':'<p>Aferîn! Gihîştî dawiya kursê yê PHP. Fêrbûyî: giyorvaok, nivîsîn, array, if/else, for/foreach, fanksiyonên, OOP, Exception, file, Session.</p>',
 'code':'<?php\nclass FerheNG {\n    private $data=[];\n    function zede($k,$v){ $this->data[$k]=$v; }\n    function bigere($k){ return $this->data[$k] ?? "Tune"; }\n    function hejmar(){ return count($this->data); }\n}\n$f=new FerheNG();\n$f->zede("av","water"); $f->zede("agir","fire"); $f->zede("erd","earth");\necho $f->bigere("av")."\\n";\necho $f->bigere("ba")."\\n";\necho "Peyvên: ".$f->hejmar()."\\n";\n?>',
 'example_output':'water\nTune\nPeyvên: 3',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە کلاسی ئازادی هەبێت کە ناو و تەمەن وەربگرێت و چاپی بکات.',
 'practice_question_ba':'Bernameyeke binivîse ko klaseke hebît ko nav û temen werdigire û çap dike.',
 'expected_output_text':'Nav: Azad, Temen: 25','solution_code':'<?php\nclass Mirov{\n    function __construct(public $nav,public $temen){}\n    function bide(){echo "Nav: $this->nav, Temen: $this->temen\\n";}\n}\n(new Mirov("Azad",25))->bide();\n?>','attempts_allowed':5},
# DONE_PHP
]
run('add_php_v2.php','PHP','-Oysj44hJLXDgdp-b9iN',php)
print('gen_php.py complete')




