#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
B='/home/donk/kurd-ai-platform'
F='https://ai-platform-adb1b-default-rtdb.firebaseio.com/'
def pv(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '['+','.join(pv(i) for i in v)+']'
    return "'"+str(v).replace('\\','\\\\').replace("'","\\'")+  "'"
def run(fname,lang,lid,LL):
    L=['<?php',f"$u='{F}';$t=trim(file_get_contents('/tmp/opencode/fb_token.txt'));$lid='{lid}';",
       "function fp($url,$d){global $t;$c=curl_init($url);curl_setopt($c,CURLOPT_RETURNTRANSFER,true);curl_setopt($c,CURLOPT_POST,true);curl_setopt($c,CURLOPT_POSTFIELDS,json_encode($d));curl_setopt($c,CURLOPT_HTTPHEADER,['Authorization: Bearer '.$t,'Content-Type: application/json']);$r=curl_exec($c);curl_close($c);return $r;}",
       "function fpa($url,$d){global $t;$c=curl_init($url);curl_setopt($c,CURLOPT_RETURNTRANSFER,true);curl_setopt($c,CURLOPT_CUSTOMREQUEST,'PATCH');curl_setopt($c,CURLOPT_POSTFIELDS,json_encode($d));curl_setopt($c,CURLOPT_HTTPHEADER,['Authorization: Bearer '.$t,'Content-Type: application/json']);$r=curl_exec($c);curl_close($c);return $r;}",
       f"fpa($u.'ferga_languages/'.$lid.'.json',['locked'=>false]);echo \"{lang} OK\\n\";",
       '$lessons=[']
    for ls in LL:
        L.append('[')
        for k,v in ls.items(): L.append(f"  {pv(k)}=>{pv(v)},")
        L.append('],')
    L+=['];',"echo 'Adding '.count($lessons).' lessons...\\n';",
        "foreach($lessons as $l){$l['langId']=$lid;$r=fp($u.'ferga_lessons.json',$l);$d=json_decode($r,true);",
        "if(isset($d['name'])){echo 'OK '.$l['order'].\"\\n\";}else{echo 'ERR '.$r.\"\\n\";exit(1);}}",
        f"echo 'Done {lang}\\n';"]
    p=os.path.join(B,fname)
    with open(p,'w',encoding='utf-8') as f: f.write('\n'.join(L)+'\n')
    print(f'Wrote {p}')
s1so='ئاستی ١ - دەستپێکردن';s1ba='ئاستا ١ - دەستپێکرن'
s2so='ئاستی ٢ - مەرج و خولگە';s2ba='ئاستا ٢ - مەرج و گەڕخستن'
s3so='ئاستی ٣ - ڕیزبندی و دەق';s3ba='ئاستا ٣ - ڕیزبندی و نڤیسین'
s4so='ئاستی ٤ - Ownership و Structs';s4ba='ئاستا ٤ - Ownership و Structs'
s5so='ئاستی ٥ - پرۆژەکان';s5ba='ئاستا ٥ - پرۆژە'
rust=[
{'order':1,'level_so':s1so,'level_ba':s1ba,'title_so':'چییە Rust؟','title_ba':'چ یە Rust؟',
 'content_so':'<p><strong>Rust</strong> زمانێکی سیستەمی بەهێزە کە Memory Safety بەبێ Garbage Collector پێشکەش دەکات. لەلایەن Mozilla لە ٢٠١٠ دروستکراوە.</p><ul><li>خێرایی وەک C/C++</li><li>بەبێ هەڵەی حافیزە</li><li>WebAssembly، سیستەم، network</li></ul>',
 'content_ba':'<p><strong>Rust</strong> زمانەکەکا سیستەمی بهێز یە کو Memory Safety بەبێ GC پێشکەش دکەت.</p><ul><li>خێرایی وەک C/C++</li><li>بەبێ هەڵەیا حافیزەیێ</li><li>WebAssembly، سیستەم</li></ul>',
 'code':'fn main() {\n    println!("Silav Kurdistane!");\n    println!("Xêrhatî bo Rust!");\n}',
 'example_output':'Silav Kurdistane!\nXêrhatî bo Rust!',
 'quiz_type':'choice','quiz_question_so':'Rust چی تایبەتمەندییەکی سەرەکی هەیە؟','quiz_question_ba':'Rust چ تایبەتمەندییا سەرەکی هەیە؟',
 'quiz_options_so':['Memory Safety بەبێ GC','Garbage Collection','بۆ وێب تەنها','ئاسانترین زمان'],
 'quiz_options_ba':['Memory Safety بەبێ GC','Garbage Collection','بو وێب تەنها','Hêsantirîn ziman'],'quiz_correct':0},

{'order':2,'level_so':s1so,'level_ba':s1ba,'title_so':'گۆڕاوەکان و let','title_ba':'گۆڕۆک û let',
 'content_so':'<p>لە Rust گۆڕاوەکان بە <code>let</code> دروست دەکرێن. بە default نەگۆڕ (immutable) ن — بۆ گۆڕین پێویستە <code>mut</code>:</p><pre>let x = 5;\nlet mut y = 10;\ny = 20; // OK\n// x = 6; // هەڵە!</pre>',
 'content_ba':'<p>د Rust دا گۆڕۆک پێ <code>let</code> drust dkêt. By default negör (immutable) — bO gorîn <code>mut</code> pêwîste:</p><pre>let x = 5;\nlet mut y = 10;\ny = 20; // OK</pre>',
 'code':'fn main() {\n    let nav = "Kurdistan";\n    let mut hejmar = 5;\n    println!("{}", nav);\n    hejmar += 3;\n    println!("{}", hejmar);\n}',
 'example_output':'Kurdistan\n8',
 'quiz_type':'choice',
 'quiz_question_so':'ئەمەی خوارەوە چی چاپ دەکات؟\nlet x = 10;\nlet y = x + 5;\nprintln!("{}", y);',
 'quiz_question_ba':'ئەڤ کودا خوارێ چ چاپ دکەت؟\nlet x = 10;\nlet y = x + 5;\nprintln!("{}", y);',
 'quiz_options_so':['15','10','5','هەڵە'],'quiz_options_ba':['15','10','5','خەلەت'],'quiz_correct':0},
{'order':3,'level_so':s1so,'level_ba':s1ba,'title_so':'جۆرەکانی داتا','title_ba':'Çeşnên Datayê',
 'content_so':'<p>جۆرە سەرەتاییەکانی Rust: <code>i32</code>، <code>f64</code>، <code>bool</code>، <code>char</code>، <code>String</code>، <code>&str</code>.</p><pre>let n: i32 = 42;\nlet f: f64 = 3.14;\nlet b: bool = true;\nlet c: char = \'K\';</pre>',
 'content_ba':'<p>Çeşnên serêtayî yên Rust: <code>i32</code>، <code>f64</code>، <code>bool</code>، <code>char</code>، <code>String</code>.</p>',
 'code':'fn main() {\n    let temen: i32 = 25;\n    let bilindi: f64 = 1.75;\n    let nav: &str = "Azad";\n    let drust: bool = true;\n    println!("{} temenî {}", nav, temen);\n    println!("bilindî: {}", bilindi);\n    println!("drust: {}", drust);\n}',
 'example_output':'Azad temenî 25\nbilindî: 1.75\ndrust: true',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\nfn main() {\n    let x = 5;\n    x = 10;\n    println!("{}", x);\n}',
 'practice_question_ba':'خەلەتا کودێ بدۆزە:\nfn main() {\n    let x = 5;\n    x = 10;\n    println!("{}", x);\n}',
 'expected_output_text':'10','solution_code':'fn main() {\n    let mut x = 5; // mut ziyad bike\n    x = 10;\n    println!("{}", x);\n}','attempts_allowed':5},
{'order':4,'level_so':s1so,'level_ba':s1ba,'title_so':'ئۆپەراتۆرەکان','title_ba':'Operatorên',
 'content_so':'<p>Rust ئۆپەراتۆرە ئاساییەکانی هەیە: <code>+</code>، <code>-</code>، <code>*</code>، <code>/</code>، <code>%</code>. ئاگاداربە: دابەشکردنی <code>i32 / i32</code> ژمارەی تەواو دەگەڕێنێتەوە.</p>',
 'content_ba':'<p>Rust operatorên: <code>+</code>، <code>-</code>، <code>*</code>، <code>/</code>، <code>%</code>. Hay be: <code>i32/i32</code> jimare tamam digerîne.</p>',
 'code':'fn main() {\n    let a: i32 = 15;\n    let b: i32 = 4;\n    println!("{}", a + b);  // 19\n    println!("{}", a - b);  // 11\n    println!("{}", a * b);  // 60\n    println!("{}", a / b);  // 3\n    println!("{}", a % b);  // 3\n    let c = a as f64 / b as f64;\n    println!("{:.2}", c);   // 3.75\n}',
 'example_output':'19\n11\n60\n3\n3\n3.75',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە قارەبووی ژمارەیەک بژمێرێت بە Rust.',
 'practice_question_ba':'Bernameyeke binivîse ko çargoşeya jimarekê bijmêre bi Rust.',
 'expected_output_text':'Qarebu(7) = 49','solution_code':'fn main() {\n    let n: i32 = 7;\n    println!("Qarebu({}) = {}", n, n*n);\n}','attempts_allowed':5},
{'order':5,'level_so':s1so,'level_ba':s1ba,'title_so':'if/else','title_ba':'if/else',
 'content_so':'<p>Rust مەرجی <code>if/else</code> هەیە. تایبەتی Rust: if دەتوانرێت وەک بەها بەکاربێت:</p><pre>let nrx = 85;\nif nrx >= 90 { println!("Taqez"); }\nelse if nrx >= 60 { println!("Bas"); }\nelse { println!("Nekefte"); }</pre>',
 'content_ba':'<p>Rust mêrca <code>if/else</code> heye. Taybetî Rust: if dikare wek behe were bikaranîn.</p>',
 'code':'fn main() {\n    let nrx = 85;\n    let asta = if nrx >= 90 { "Taqez" }\n               else if nrx >= 70 { "Bas" }\n               else if nrx >= 50 { "Navend" }\n               else { "Nekefte" };\n    println!("{}", asta);\n}',
 'example_output':'Bas',
 'quiz_type':'choice','quiz_question_so':'ئەگەر nrx=45 بێت، چی چاپ دەبێت؟','quiz_question_ba':'Ger nrx=45 be, çi tê çapkirin?',
 'quiz_options_so':['Nekefte','Navend','Bas','Taqez'],'quiz_options_ba':['Nekefte','Navend','Bas','Taqez'],'quiz_correct':0},
{'order':6,'level_so':s1so,'level_ba':s1ba,'title_so':'match','title_ba':'match',
 'content_so':'<p><code>match</code> لە Rust وەک switch باشتر: هەموو حالەتەکان دەبێت پووشەبن:</p><pre>match n {\n    1 => println!("Yek"),\n    2 | 3 => println!("Du an se"),\n    _ => println!("Tiştekî din"),\n}</pre>',
 'content_ba':'<p><code>match</code> di Rust wek switch çêtir e: hemî halet divê tiji bin:</p>',
 'code':'fn main() {\n    let roj = 3;\n    match roj {\n        1 => println!("Duşem"),\n        2 => println!("Sêşem"),\n        3 => println!("Çarşem"),\n        4 => println!("Pênçşem"),\n        5 => println!("Înî"),\n        _ => println!("Dawiya heftê"),\n    }\n}',
 'example_output':'Çarşem',
 'quiz_type':'choice',
 'quiz_question_so':'ئەمەی خوارەوە چی چاپ دەکات؟\nlet x = 5;\nmatch x { 1=>println!("yek"), 5=>println!("pênc"), _=>println!("din") }',
 'quiz_question_ba':'ئەڤ کودا خوارێ چ چاپ دکەت؟\nlet x = 5;\nmatch x { 1=>println!("yek"), 5=>println!("pênc"), _=>println!("din") }',
 'quiz_options_so':['pênc','yek','din','هەڵە'],'quiz_options_ba':['pênc','yek','din','خەلەت'],'quiz_correct':0},

# L2: loops
{'order':7,'level_so':s2so,'level_ba':s2ba,'title_so':'خولگەی loop و while','title_ba':'loop û while',
 'content_so':'<p>Rust خولگەی <code>loop</code> (بێ مەرج)، <code>while</code>، و <code>for..in</code> هەیە:</p><pre>let mut n=0;\nloop { n+=1; if n==5 { break; } }\nwhile n>0 { n-=1; }</pre>',
 'content_ba':'<p>Rust gêrxistinên: <code>loop</code>، <code>while</code>، û <code>for..in</code>:</p>',
 'code':'fn main() {\n    let mut n=0;\n    loop { n+=1; if n>=5 { break; } }\n    println!("loop: {}", n);\n    let mut x=10;\n    while x>0 { print!("{} ",x); x-=3; }\n    println!();\n}',
 'example_output':'loop: 5\n10 7 4 1 ',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\nfn main() {\n    let mut n = 0;\n    while n < 3 {\n        println!("{}", n);\n    }\n}',
 'practice_question_ba':'Xeleta kodê bidoze:\nfn main() {\n    let mut n = 0;\n    while n < 3 {\n        println!("{}", n);\n    }\n}',
 'expected_output_text':'0\n1\n2','solution_code':'fn main() {\n    let mut n = 0;\n    while n < 3 {\n        println!("{}", n);\n        n += 1; // n++ tune di Rust de, n+=1 bikar bîne\n    }\n}','attempts_allowed':5},
{'order':8,'level_so':s2so,'level_ba':s2ba,'title_so':'for..in و Range','title_ba':'for..in û Range',
 'content_so':'<p><code>for..in</code> بۆ خولاندنی ئاراکان و range: <code>1..=5</code> (گونجاندنی) <code>1..5</code> (دەرجووی):</p><pre>for i in 1..=5 { println!("{}", i); }\nfor x in [10,20,30] { println!("{}", x); }</pre>',
 'content_ba':'<p><code>for..in</code> bO xolandina arrayan û range:</p>',
 'code':'fn main() {\n    for i in 1..=5 { print!("{} ", i); }\n    println!();\n    let bajer = ["Hewler","Silemani","Duhok"];\n    for (idx, b) in bajer.iter().enumerate() {\n        println!("{}. {}", idx+1, b);\n    }\n}',
 'example_output':'1 2 3 4 5 \n1. Hewler\n2. Silemani\n3. Duhok',
 'quiz_type':'choice',
 'quiz_question_so':'ئەمەی خوارەوە چی چاپ دەکات؟\nfor i in 0..3 { print!("{} ", i); }',
 'quiz_question_ba':'ئەڤ کودا خوارێ چ چاپ دکەت؟\nfor i in 0..3 { print!("{} ", i); }',
 'quiz_options_so':['0 1 2 ','0 1 2 3 ','1 2 3 ','هەڵە'],'quiz_options_ba':['0 1 2 ','0 1 2 3 ','1 2 3 ','خەلەت'],'quiz_correct':0},
{'order':9,'level_so':s2so,'level_ba':s2ba,'title_so':'break و continue','title_ba':'break û continue',
 'content_so':'<p><code>break</code> خولگەکە دادەوەستێنێت. <code>continue</code> گەڕانی ئێستا تێپەردەی دەکات.</p>',
 'content_ba':'<p><code>break</code> gêrxistinê datestênit. <code>continue</code> gêrana niha têperde dike.</p>',
 'code':'fn main() {\n    for i in 1..=10 {\n        if i == 7 { break; }\n        if i % 2 == 0 { continue; }\n        print!("{} ", i);\n    }\n    println!();\n}',
 'example_output':'1 3 5 ',
 'quiz_type':'choice',
 'quiz_question_so':'ئەمەی خوارەوە چی چاپ دەکات؟\nfor i in 1..=5 { if i==3 { continue; } print!("{} ",i); }',
 'quiz_question_ba':'ئەڤ کودا خوارێ چ چاپ دکەت؟\nfor i in 1..=5 { if i==3 { continue; } print!("{} ",i); }',
 'quiz_options_so':['1 2 4 5 ','1 2 3 4 5 ','1 2 ','هەڵە'],'quiz_options_ba':['1 2 4 5 ','1 2 3 4 5 ','1 2 ','خەلەت'],'quiz_correct':0},
{'order':10,'level_so':s2so,'level_ba':s2ba,'title_so':'فەنکشن','title_ba':'Fanksiyonên',
 'content_so':'<p>فەنکشن لە Rust بە <code>fn</code>. جۆری گەڕانەوە دیاری دەکرێت بە <code>-></code>:</p><pre>fn kot(a: i32, b: i32) -> i32 { a + b }\nprintln!("{}", kot(3, 5)); // 8</pre>',
 'content_ba':'<p>Fanksiyonên di Rust de pê <code>fn</code>. Cureyê gerêdanê pê <code>-></code> diyar dike:</p>',
 'code':'fn kot(a: i32, b: i32) -> i32 { a + b }\nfn jote(n: i32) -> bool { n % 2 == 0 }\nfn xêrhatî(nav: &str) -> String { format!("Silav, {}!", nav) }\nfn main() {\n    println!("{}", kot(4,6));\n    println!("{}", jote(7));\n    println!("{}", xêrhatî("Kurdistan"));\n}',
 'example_output':'10\nfalse\nSilav, Kurdistan!',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\nfn giştî(a: i32, b: i32) -> i32 {\n    return a + b;\n    a * b\n}',
 'practice_question_ba':'Xeleta kodê bidoze:\nfn giştî(a: i32, b: i32) -> i32 {\n    return a + b;\n    a * b\n}',
 'expected_output_text':'15','solution_code':'fn giştî(a: i32, b: i32) -> i32 {\n    a + b // return bê "return" keyword — an jî return bikar bîne û a*b jê bibe\n}\nfn main() { println!("{}", giştî(7,8)); }','attempts_allowed':5},
{'order':11,'level_so':s2so,'level_ba':s2ba,'title_so':'Ownership (خاوەندایەتی)','title_ba':'Ownership',
 'content_so':'<p>Ownership سیستەمی مانایەکی Rust یە. هەر بەها تەنها یەک خاوەندی هەیە. کاتی گواستنەوە (<code>move</code>) خاوەنی کۆن بەتاڵ دەبێت.</p>',
 'content_ba':'<p>Ownership sîstema bîranîna Rust e. Her behe tenê xawanekê heye. Dema veguhastinê (move) xawanê kevin betale dibe.</p>',
 'code':'fn main() {\n    let s1 = String::from("Kurdistan");\n    let s2 = s1; // s1 moved bo s2\n    // println!("{}", s1); // Hêle: moved!\n    println!("{}", s2);\n    let n1: i32 = 5;\n    let n2 = n1; // Copy (ne Move) bO primitive types\n    println!("{} {}", n1, n2);\n}',
 'example_output':'Kurdistan\n5 5',
 'quiz_type':'choice','quiz_question_so':'لە Rust کاتی move چ دەبێتە سەر گۆڕاوی کۆن؟','quiz_question_ba':'Di Rust de gava move çi dibe bo giyorvaeka kevin?',
 'quiz_options_so':['بەتاڵ دەبێت (invalid)','کۆپی دەبێت','سفر دەبێت','نەگۆڕ دەمێنێتەوە'],
 'quiz_options_ba':['Betale dibe (invalid)','Copy dibe','Sifir dibe','Negör dimêne'],'quiz_correct':0},
{'order':12,'level_so':s2so,'level_ba':s2ba,'title_so':'References و Borrowing','title_ba':'References û Borrowing',
 'content_so':'<p>Reference (<code>&</code>) ڕێگەت دەدات بەبێ move بەها بەکاربهێنیت. ئەمە <strong>borrowing</strong>ە:</p><pre>fn drêjayî(s: &String) -> usize { s.len() }\nlet s = String::from("Kurd");\nprintln!("{}", drêjayî(&s));\nprintln!("{}", s); // هێشتا درووستە</pre>',
 'content_ba':'<p>Reference (<code>&</code>) bê move bikaranîna behe dide: <strong>borrowing</strong>:</p>',
 'code':'fn drêjayî(s: &String) -> usize { s.len() }\nfn mezin_bike(s: &mut String) { s.push_str(" baş e!"); }\nfn main() {\n    let s = String::from("Rust");\n    println!("{}", drêjayî(&s));\n    let mut t = String::from("Rust");\n    mezin_bike(&mut t);\n    println!("{}", t);\n}',
 'example_output':'4\nRust baş e!',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\nfn test(s: &String) {\n    s.push_str(" zede");\n}\nfn main() {\n    let s = String::from("Kurd");\n    test(&s);\n    println!("{}", s);\n}',
 'practice_question_ba':'Xeleta kodê bidoze:\nfn test(s: &String) {\n    s.push_str(" zede");\n}\nfn main() {\n    let s = String::from("Kurd");\n    test(&s);\n    println!("{}", s);\n}',
 'expected_output_text':'Kurd zede','solution_code':'fn test(s: &mut String) { // &mut lazime bO guhartin\n    s.push_str(" zede");\n}\nfn main() {\n    let mut s = String::from("Kurd"); // mut lazime\n    test(&mut s);\n    println!("", s);\n}','attempts_allowed':5},

# L3: Structs, enums, Vec
{'order':13,'level_so':s3so,'level_ba':s3ba,'title_so':'Vec (ئارای ئەندازەدۆز)','title_ba':'Vec (ئارایا Endazedoz)',
 'content_so':'<p><code>Vec</code> ئارایەکی ئەندازەدۆز (dynamic array) یە لە Rust:</p><pre>let mut v: Vec<i32> = Vec::new();\nv.push(1); v.push(2);\nfor x in &v { println!("{}", x); }</pre>',
 'content_ba':'<p><code>Vec</code> arraya dinamîk e di Rust de:</p>',
 'code':'fn main() {\n    let mut hejmar: Vec<i32> = vec![5,2,8,1,9];\n    hejmar.push(7);\n    hejmar.sort();\n    println!("{:?}", hejmar);\n    println!("Max: {}", hejmar.iter().max().unwrap());\n    println!("Drêjayî: {}", hejmar.len());\n}',
 'example_output':'[1, 2, 5, 7, 8, 9]\nMax: 9\nDrêjayî: 6',
 'quiz_type':'choice','quiz_question_so':'Vec::new() چی دەگەڕێنێتەوە؟','quiz_question_ba':'Vec::new() çi digerîne?',
 'quiz_options_so':['Vec بەتاڵ','Vec بە بەها','null','هەڵە'],'quiz_options_ba':['Vec betale','Vec bi behe','null','xelat'],'quiz_correct':0},
{'order':14,'level_so':s3so,'level_ba':s3ba,'title_so':'Struct','title_ba':'Struct',
 'content_so':'<p>Struct داتای تێکەڵ کۆ دەکاتەوە. لە Rust گۆڕانکاری پێویستە <code>mut</code>:</p><pre>struct Mirov { nav: String, temen: u32 }\nlet m = Mirov { nav: String::from("Kurd"), temen: 25 };</pre>',
 'content_ba':'<p>Struct daneyan tê de dicivîne. Di Rust de guhartin pê <code>mut</code> pêwîste:</p>',
 'code':'struct Xwendekar { nav: String, nrx: f64 }\nimpl Xwendekar {\n    fn new(nav: &str, nrx: f64) -> Xwendekar {\n        Xwendekar { nav: String::from(nav), nrx }\n    }\n    fn derbaz(&self) -> bool { self.nrx >= 50.0 }\n    fn bide(&self) { println!("{}: {} ({})", self.nav, self.nrx, if self.derbaz(){"Derbaz"}else{"Nekefte"}); }\n}\nfn main() {\n    let x = Xwendekar::new("Azad", 88.5);\n    x.bide();\n    let y = Xwendekar::new("Baran", 45.0);\n    y.bide();\n}',
 'example_output':'Azad: 88.5 (Derbaz)\nBaran: 45 (Nekefte)',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\nstruct Mirov { nav: String }\nfn main() {\n    let m = Mirov { nav: "Kurd" };\n    println!("{}", m.nav);\n}',
 'practice_question_ba':'Xeleta kodê bidoze:\nstruct Mirov { nav: String }\nfn main() {\n    let m = Mirov { nav: "Kurd" };\n    println!("{}", m.nav);\n}',
 'expected_output_text':'Kurd','solution_code':'struct Mirov { nav: String }\nfn main() {\n    let m = Mirov { nav: String::from("Kurd") }; // &str bo String::from lazime\n    println!("{}", m.nav);\n}','attempts_allowed':5},
{'order':15,'level_so':s3so,'level_ba':s3ba,'title_so':'Enum','title_ba':'Enum',
 'content_so':'<p>Enum جۆرێکه کە چەند بەهای دیاریکراو هەیە. لەگەڵ match بەکاردێت:</p><pre>enum Asta { Destpêk, Navend, Pêşkewtu }\nlet a = Asta::Navend;</pre>',
 'content_ba':'<p>Enum cureyeke ko çend behe yên diyarkirî heye. Ligel match tê bikaranîn:</p>',
 'code':'enum Reng { Sor, Kesk, Şîn, Din(String) }\nfn bide(r: Reng) {\n    match r {\n        Reng::Sor => println!("Sor"),\n        Reng::Kesk => println!("Kesk"),\n        Reng::Şîn => println!("Şîn"),\n        Reng::Din(nav) => println!("Rengê din: {}", nav),\n    }\n}\nfn main() {\n    bide(Reng::Kesk);\n    bide(Reng::Din(String::from("Zer")));\n}',
 'example_output':'Kesk\nRengê din: Zer',
 'quiz_type':'choice','quiz_question_so':'ئەمەی خوارەوە چی چاپ دەکات؟\nenum Dir {Bakur, Başûr, Rojhilat, Rojava}\nlet d = Dir::Başûr;\nmatch d { Dir::Bakur=>println!("N"), Dir::Başûr=>println!("S"), _=>println!("E/W") }',
 'quiz_question_ba':'ئەڤ کودا خوارێ چ چاپ دکەت؟\nenum Dir {Bakur,Başûr,Rojhilat,Rojava}\nlet d=Dir::Başûr;\nmatch d{Dir::Bakur=>println!("N"),Dir::Başûr=>println!("S"),_=>println!("E/W")}',
 'quiz_options_so':['S','N','E/W','هەڵە'],'quiz_options_ba':['S','N','E/W','xelat'],'quiz_correct':0},
{'order':16,'level_so':s3so,'level_ba':s3ba,'title_so':'Option<T>','title_ba':'Option<T>',
 'content_so':'<p><code>Option<T></code> بەهایەکی کە دەتوانێت هەبێت (<code>Some</code>) یان نەبێت (<code>None</code>). جێگۆڕی null یە:</p><pre>fn dabesh(a:i32,b:i32)->Option<i32>{\n    if b==0 {None} else {Some(a/b)}\n}</pre>',
 'content_ba':'<p><code>Option<T></code> behe ya dikare hebe (Some) an nebe (None). Şûna null e:</p>',
 'code':'fn mezin(v: &Vec<i32>) -> Option<i32> {\n    if v.is_empty() { None }\n    else { Some(*v.iter().max().unwrap()) }\n}\nfn main() {\n    let v = vec![3,7,1,9,4];\n    match mezin(&v) {\n        Some(m) => println!("Mezin: {}", m),\n        None => println!("Vala ye"),\n    }\n    let empty: Vec<i32> = vec![];\n    println!("{}", mezin(&empty).unwrap_or(-1));\n}',
 'example_output':'Mezin: 9\n-1',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە ژمارەیەک وەک Option وەربگرێت و بهیا دووتایی چاپ بکات یان "None" ئەگەر نەبێت.',
 'practice_question_ba':'Bernameyeke binivîse ko jimarekê wek Option wergire û bihaya du-alî çap bike an "None".',
 'expected_output_text':'Some(10)\nNone','solution_code':'fn du(x: Option<i32>) -> Option<i32> {\n    x.map(|n| n*2)\n}\nfn main() {\n    println!("{:?}", du(Some(5)));\n    println!("{:?}", du(None));\n}','attempts_allowed':5},
{'order':17,'level_so':s3so,'level_ba':s3ba,'title_so':'String و &str','title_ba':'String û &str',
 'content_so':'<p>لە Rust دوو جۆری دەق هەن: <code>String</code> (خاوەندایەتییە، گۆڕێکار) و <code>&str</code> (slice، خوێندنی تەنها).</p>',
 'content_ba':'<p>Di Rust de du cureyên nivîsînê: <code>String</code> (xawendar, gêrêkar) û <code>&str</code> (slice, xwendina tenê).</p>',
 'code':'fn xêrhatî(nav: &str) -> String {\n    format!("Silav, {}!", nav)\n}\nfn main() {\n    let s1: &str = "Kurdistan";\n    let s2: String = String::from("Hewler");\n    let s3 = s1.to_string() + " & " + &s2;\n    println!("{}", s3);\n    println!("{}", xêrhatî(s1));\n    println!("{}", s2.len());\n    println!("{}", s2.contains("Hew"));\n}',
 'example_output':'Kurdistan & Hewler\nSilav, Kurdistan!\n6\ntrue',
 'quiz_type':'choice','quiz_question_so':'فەرقی String و &str چییە؟','quiz_question_ba':'Cudahiya String û &str çi ye?',
 'quiz_options_so':['String خاوەندایەتییە، &str slice یە','هەر دووکیان یەکسانن','String کورتتەرە','&str خاوەندایەتییە'],
 'quiz_options_ba':['String xawendar e, &str slice ye','Her du yek in','String kurtir e','&str xawendar e'],'quiz_correct':0},
{'order':18,'level_so':s3so,'level_ba':s3ba,'title_so':'HashMap','title_ba':'HashMap',
 'content_so':'<p><code>HashMap</code> کلیل-بەها ستۆر دەکات لە Rust:</p><pre>use std::collections::HashMap;\nlet mut m = HashMap::new();\nm.insert("av", "water");\nprintln!("{}", m["av"]);</pre>',
 'content_ba':'<p><code>HashMap</code> kilîl-behe tê de diparêze di Rust de:</p>',
 'code':'use std::collections::HashMap;\nfn main() {\n    let mut xalên: HashMap<&str,i32> = HashMap::new();\n    xalên.insert("Azad", 92);\n    xalên.insert("Baran", 85);\n    xalên.insert("Ciya", 78);\n    for (nav, nrx) in &xalên {\n        println!("{}: {}", nav, nrx);\n    }\n    println!("Jimare: {}", xalên.len());\n    println!("{}", xalên.get("Azad").unwrap_or(&0));\n}',
 'example_output':'Azad: 92\nBaran: 85\nCiya: 78\nJimare: 3\n92',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە فەرهەنگی کوردی-ئینگلیزی لەگەڵ HashMap دروست بکات.',
 'practice_question_ba':'Bernameyeke binivîse ko ferhengeke Kurdî-Înglîzî ligel HashMap çêbike.',
 'expected_output_text':'av = water\nagir = fire','solution_code':'use std::collections::HashMap;\nfn main() {\n    let mut f=HashMap::new();\n    f.insert("av","water");\n    f.insert("agir","fire");\n    for (k,v) in &f { println!("{} = {}",k,v); }\n}','attempts_allowed':5},

# L4: Traits, closures, iterators
{'order':19,'level_so':s4so,'level_ba':s4ba,'title_so':'Traits','title_ba':'Traits',
 'content_so':'<p>Trait لە Rust وەک Interface یە — دیاری دەکات کلاسێک/struct چی پەیدا دەکات:</p><pre>trait Danasîn { fn bide(&self); }\nimpl Danasîn for Mirov { fn bide(&self){...} }</pre>',
 'content_ba':'<p>Trait di Rust de wek Interface ye — diyar dike struct çi peyda dike:</p>',
 'code':'trait Dengdêr { fn deng(&self) -> &str; }\nstruct Se { nav: String }\nstruct Pisîk { nav: String }\nimpl Dengdêr for Se { fn deng(&self) -> &str { "Haw!" } }\nimpl Dengdêr for Pisîk { fn deng(&self) -> &str { "Mêw!" } }\nfn axivîn(d: &dyn Dengdêr) { println!("{}", d.deng()); }\nfn main() {\n    let s = Se { nav: String::from("Zato") };\n    let p = Pisîk { nav: String::from("Mîla") };\n    axivîn(&s); axivîn(&p);\n}',
 'example_output':'Haw!\nMêw!',
 'quiz_type':'choice','quiz_question_so':'Trait لە Rust بۆ چی بەکاردێت؟','quiz_question_ba':'Trait di Rust de bO çi tê bikaranîn?',
 'quiz_options_so':['دیاریکردنی رەفتار','هەلگرتنی داتا','دروستکردنی ئۆبجێکت','خولاندنی ئارا'],
 'quiz_options_ba':['Diyarkirina reftar','Hilgirtina dane','Çêkirina obejkt','Xolandina array'],'quiz_correct':0},
{'order':20,'level_so':s4so,'level_ba':s4ba,'title_so':'Closures','title_ba':'Closures',
 'content_so':'<p>Closure فەنکشنێکی ناوخۆییە کە گۆڕاوی ژینگەکەی دەگرێتەوە:</p><pre>let du = |x| x * 2;\nprintln!("{}", du(5)); // 10\nlet nrx = 10;\nlet zêde = |x| x + nrx; // nrx capture</pre>',
 'content_ba':'<p>Closure fanksiyoneke hundirîn e ko giyorvaokên hawirdorê degirite:</p>',
 'code':'fn main() {\n    let du = |x: i32| x * 2;\n    let kot = |a: i32, b: i32| a + b;\n    println!("{}", du(7));\n    println!("{}", kot(4, 5));\n    let nrx = 10;\n    let zêde = |x| x + nrx;\n    println!("{}", zêde(5));\n    let v: Vec<i32> = (1..=5).map(|x| x * x).collect();\n    println!("{:?}", v);\n}',
 'example_output':'14\n9\n15\n[1, 4, 9, 16, 25]',
 'quiz_type':'choice',
 'quiz_question_so':'ئەمەی خوارەوە چی چاپ دەکات؟\nlet m = |x:i32| x*x;\nprintln!("{}", m(6));',
 'quiz_question_ba':'ئەڤ کودا خوارێ چ چاپ دکەت؟\nlet m = |x:i32| x*x;\nprintln!("{}", m(6));',
 'quiz_options_so':['36','12','6','هەڵە'],'quiz_options_ba':['36','12','6','xelat'],'quiz_correct':0},
{'order':21,'level_so':s4so,'level_ba':s4ba,'title_so':'Iterators','title_ba':'Iterators',
 'content_so':'<p>Iterator میتۆدەکانی chain دەکات: <code>.map()</code>، <code>.filter()</code>، <code>.collect()</code>، <code>.sum()</code>، <code>.fold()</code>.</p>',
 'content_ba':'<p>Iterator metodên chain dike: <code>.map()</code>، <code>.filter()</code>، <code>.collect()</code>.</p>',
 'code':'fn main() {\n    let v = vec![1,2,3,4,5,6,7,8,9,10];\n    let jote: Vec<i32> = v.iter().filter(|&&x| x%2==0).cloned().collect();\n    println!("{:?}", jote);\n    let kot: i32 = v.iter().sum();\n    println!("Kot: {}", kot);\n    let qarebu: Vec<i32> = v.iter().map(|&x| x*x).collect();\n    println!("{:?}", qarebu);\n}',
 'example_output':'[2, 4, 6, 8, 10]\nKot: 55\n[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]',
 'quiz_type':'practice',
 'practice_question_so':'هەڵەی کۆد بدۆزەرەوە:\nlet v = vec![1,2,3];\nlet r = v.map(|x| x*2).collect::<Vec<_>>();\nprintln!("{:?}", r);',
 'practice_question_ba':'Xeleta kodê bidoze:\nlet v = vec![1,2,3];\nlet r = v.map(|x| x*2).collect::<Vec<_>>();\nprintln!("{:?}", r);',
 'expected_output_text':'[2, 4, 6]','solution_code':'fn main() {\n    let v = vec![1,2,3];\n    let r: Vec<_> = v.iter().map(|x| x*2).collect(); // .iter() lazime\n    println!("{:?}", r);\n}','attempts_allowed':5},
{'order':22,'level_so':s4so,'level_ba':s4ba,'title_so':'Result و Error Handling','title_ba':'Result û Error Handling',
 'content_so':'<p><code>Result<T,E></code> جێگۆڕی exception یە لە Rust: <code>Ok(val)</code> یان <code>Err(e)</code>. بە <code>?</code> بە ئاسانی propagate دەکرێت.</p>',
 'content_ba':'<p><code>Result<T,E></code> şûna exception e di Rust de: <code>Ok(val)</code> an <code>Err(e)</code>.</p>',
 'code':'use std::num::ParseIntError;\nfn parse(s: &str) -> Result<i32, ParseIntError> {\n    s.trim().parse::<i32>()\n}\nfn main() {\n    match parse("42") {\n        Ok(n) => println!("OK: {}", n),\n        Err(e) => println!("Hêle: {}", e),\n    }\n    match parse("abc") {\n        Ok(n) => println!("OK: {}", n),\n        Err(e) => println!("Hêle: {}", e),\n    }\n}',
 'example_output':'OK: 42\nHêle: invalid digit found in string',
 'quiz_type':'choice',
 'quiz_question_so':'ئەمەی خوارەوە چی چاپ دەکات؟\nlet r: Result<i32,&str> = Ok(5);\nprintln!("{}", r.unwrap_or(0));',
 'quiz_question_ba':'ئەڤ کودا خوارێ چ چاپ دکەت؟\nlet r: Result<i32,&str> = Ok(5);\nprintln!("{}", r.unwrap_or(0));',
 'quiz_options_so':['5','0','Err','هەڵە'],'quiz_options_ba':['5','0','Err','xelat'],'quiz_correct':0},
{'order':23,'level_so':s4so,'level_ba':s4ba,'title_so':'Lifetimes','title_ba':'Lifetimes',
 'content_so':'<p>Lifetime دیاری دەکات reference چەندێک ژیاو. لە فەنکشنەکانی کە reference دەگەڕێنەوە پێویستە:</p><pre>fn dirêjtirîn<\'a>(a: &\'a str, b: &\'a str) -> &\'a str {\n    if a.len() > b.len() { a } else { b }\n}</pre>',
 'content_ba':'<p>Lifetime diyar dike reference çend jiyo. Di fanksiyonên ko reference digerîne pêwîste:</p>',
 'code':'fn dirêjtirîn<\'a>(a: &\'a str, b: &\'a str) -> &\'a str {\n    if a.len() >= b.len() { a } else { b }\n}\nfn main() {\n    let s1 = String::from("Kurdistan");\n    let result;\n    {\n        let s2 = String::from("Kurd");\n        result = dirêjtirîn(&s1, &s2);\n        println!("Dirêjtirîn: {}", result);\n    }\n}',
 'example_output':'Dirêjtirîn: Kurdistan',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە لەگەڵ lifetime کورتترین دەق لە دوو ئیتەم دەبینێت.',
 'practice_question_ba':'Bernameyeke binivîse ko ligel lifetime kurttirîn nivîsîn ji du tiştan bibîne.',
 'expected_output_text':'Kurttirîn: Kurd','solution_code':'fn kurttirîn<\'a>(a: &\'a str, b: &\'a str) -> &\'a str {\n    if a.len() <= b.len() {a} else {b}\n}\nfn main() {\n    println!("Kurttirîn: {}", kurttirîn("Kurd","Kurdistan"));\n}','attempts_allowed':5},
{'order':24,'level_so':s4so,'level_ba':s4ba,'title_so':'Generic Functions','title_ba':'Generic Functions',
 'content_so':'<p>Generic فەنکشن دەتوانرێت لەگەڵ هەر جۆرێک کاربکات:</p><pre>fn bide<T: std::fmt::Display>(val: T) {\n    println!("{}", val);\n}\nbide(42); bide("Kurd"); bide(3.14);</pre>',
 'content_ba':'<p>Generic fanksiyonên dikarin ligel her cureyê biçin:</p>',
 'code':'fn mezin<T: PartialOrd>(a: T, b: T) -> T {\n    if a >= b { a } else { b }\n}\nfn bide<T: std::fmt::Debug>(v: &[T]) {\n    for x in v { print!("{:?} ", x); }\n    println!();\n}\nfn main() {\n    println!("{}", mezin(10, 7));\n    println!("{}", mezin("Kurd", "Xurt"));\n    bide(&[1,2,3,4,5]);\n}',
 'example_output':'10\nXurt\n1 2 3 4 5 ',
 'quiz_type':'choice','quiz_question_so':'Generic لە Rust بۆ چی بەکاردێت؟','quiz_question_ba':'Generic di Rust de bO çi tê bikaranîn?',
 'quiz_options_so':['کۆد دووبارە بەکارهێنان بۆ جۆرەکانی جیاواز','تەنها بۆ i32','تەنها بۆ String','هیچ پێویستی پێ نییە'],
 'quiz_options_ba':['Kodê ji nû ve bikaranîn bO cureyan','Tenê bO i32','Tenê bO String','Tu pêdivî pê tune'],'quiz_correct':0},
# L5: Projects
{'order':25,'level_so':s5so,'level_ba':s5ba,'title_so':'پرۆژە: بەڕێوەبردنی خوێندکار','title_ba':'Proje: Xwendekarên',
 'content_so':'<p>پرۆژەی یەکەم — سیستەمی ئەرشیفی خوێندکاران بە Struct:</p>',
 'content_ba':'<p>Projeya yekem — sîstema erşîva xwendekaran bi Struct:</p>',
 'code':'#[derive(Debug)]\nstruct Xwendekar { nav: String, nrx: f64 }\nimpl Xwendekar {\n    fn new(nav: &str, nrx: f64) -> Self { Xwendekar{nav:String::from(nav),nrx} }\n    fn ast(&self) -> &str {\n        if self.nrx>=90.0{"Taqez"} else if self.nrx>=70.0{"Baş"} else if self.nrx>=50.0{"Navend"} else{"Nekefte"}\n    }\n}\nfn main() {\n    let mut lîste = vec![\n        Xwendekar::new("Azad",92.0),\n        Xwendekar::new("Baran",75.0),\n        Xwendekar::new("Ciya",48.0),\n    ];\n    lîste.sort_by(|a,b| b.nrx.partial_cmp(&a.nrx).unwrap());\n    for x in &lîste { println!("{}: {} [{}]", x.nav, x.nrx, x.ast()); }\n    let navend: f64 = lîste.iter().map(|x|x.nrx).sum::<f64>()/lîste.len() as f64;\n    println!("Navend: {:.1}", navend);\n}',
 'example_output':'Azad: 92 [Taqez]\nBaran: 75 [Baş]\nCiya: 48 [Nekefte]\nNavend: 71.7',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە Vec<i32> وەربگرێت و ژمارەی ئەوانەی کە %3==0 ن بژمێرێت.',
 'practice_question_ba':'Bernameyeke binivîse ko Vec<i32> bigire û hejmara wan ko %3==0 bijmêre.',
 'expected_output_text':'Jimare: 3','solution_code':'fn jimareyê_se(v: &Vec<i32>) -> usize { v.iter().filter(|&&x|x%3==0).count() }\nfn main() {\n    let v=vec![3,5,6,9,11,12];\n    println!("Jimare: {}",jimareyê_se(&v));\n}','attempts_allowed':5},
{'order':26,'level_so':s5so,'level_ba':s5ba,'title_so':'پرۆژە: ماشێنی ژمارەکردن','title_ba':'Proje: Mêşîna Jimarê',
 'content_so':'<p>پرۆژەی دووەم — ماشێنی ژمارەکردنی سادە:</p>',
 'content_ba':'<p>Projeya duyem — mêşîna jimarêkirinê:</p>',
 'code':'fn hesab(a:f64, op:char, b:f64) -> Result<f64,String> {\n    match op {\n        \'+\' => Ok(a+b),\n        \'-\' => Ok(a-b),\n        \'*\' => Ok(a*b),\n        \'/\' => if b!=0.0{Ok(a/b)}else{Err("Dabêşkirina bi sifir!".to_string())},\n        _ => Err(format!("Operator nenas: {}", op))\n    }\n}\nfn main() {\n    let tests = [(10.0,\'+\',5.0),(20.0,\'-\',8.0),(6.0,\'*\',7.0),(15.0,\'/\',3.0),(5.0,\'/\',0.0)];\n    for (a,op,b) in tests {\n        match hesab(a,op,b) {\n            Ok(r) => println!("{} {} {} = {}",a,op,b,r),\n            Err(e) => println!("Hêle: {}",e),\n        }\n    }\n}',
 'example_output':'10 + 5 = 15\n20 - 8 = 12\n6 * 7 = 42\n15 / 3 = 5\nHêle: Dabêşkirina bi sifir!',
 'quiz_type':'choice','quiz_question_so':'Result::Ok چییە لە Rust؟','quiz_question_ba':'Result::Ok çi ye di Rust de?',
 'quiz_options_so':['دەرئەنجامی سەرکەوتوو','هەڵەیەک','هیچ','boolean'],
 'quiz_options_ba':['Encama serkewtu','Helayeke','Tu tişt','boolean'],'quiz_correct':0},
{'order':27,'level_so':s5so,'level_ba':s5ba,'title_so':'پرۆژە: فەرهەنگی کوردی','title_ba':'Proje: Ferhengê Kurdî',
 'content_so':'<p>پرۆژەی سێیەم — دیکشنەری کوردی-ئینگلیزی بە HashMap:</p>',
 'content_ba':'<p>Projeya sêyem — Dîksiyonêra Kurdî-Înglîzî bi HashMap:</p>',
 'code':'use std::collections::HashMap;\nfn main() {\n    let mut ferheng: HashMap<&str,&str> = HashMap::new();\n    let peyvên = [("av","water"),("agir","fire"),("erd","earth"),("ba","wind"),("roj","sun"),("av","water")];\n    for (k,v) in &peyvên { ferheng.insert(k,v); }\n    let lêgerin = ["av","hesp","roj"];\n    for peyvek in &lêgerin {\n        match ferheng.get(peyvek) {\n            Some(w) => println!("{} = {}",peyvek,w),\n            None => println!("{}: tune di ferheNGê de",peyvek),\n        }\n    }\n    println!("Jimare: ", ferheng.len());\n}',
 'example_output':'av = water\nhesp: tune di ferheNGê de\nroj = sun\nJimare: 5',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە ژمارەی پەیوەندکراوی هاوشێوەکانی String لە Vec دا بژمێرێت.',
 'practice_question_ba':'Bernameyeke binivîse ko hejmara peyvên wekhev di Vec de bijmêre.',
 'expected_output_text':'Kurd: 2\nRust: 1','solution_code':'use std::collections::HashMap;\nfn main() {\n    let v=vec!["Kurd","Rust","Kurd","Java","Rust","Kurd"];\n    let mut m:HashMap<&str,i32>=HashMap::new();\n    for w in v { *m.entry(w).or_insert(0)+=1; }\n    for (k,v) in &m { if *v>1 { println!("{}: {}",k,v); } }\n}','attempts_allowed':5},
{'order':28,'level_so':s5so,'level_ba':s5ba,'title_so':'File I/O','title_ba':'File I/O',
 'content_so':'<p>خوێندن و نووسینی فایل لە Rust:</p><pre>use std::fs;\nfs::write("test.txt","Silav")?;\nlet nav = fs::read_to_string("test.txt")?;</pre>',
 'content_ba':'<p>Xwendin û nivîsîna file di Rust de:</p>',
 'code':'use std::fs;\nuse std::io::Write;\nfn main() -> std::io::Result<()> {\n    fs::write("/tmp/kurd.txt","Silav Kurdistan!\\nRust bax e\\n")?;\n    let nav = fs::read_to_string("/tmp/kurd.txt")?;\n    print!("{}", nav);\n    let rêzan: Vec<&str> = nav.lines().collect();\n    println!("Jimare: {}", rêzan.len());\n    fs::remove_file("/tmp/kurd.txt")?;\n    Ok(())\n}',
 'example_output':'Silav Kurdistan!\nRust bax e\nJimare: 2',
 'quiz_type':'choice','quiz_question_so':'<code>?</code> ئۆپەراتۆری لە Rust چییە؟','quiz_question_ba':'<code>?</code> operator di Rust de çi ye?',
 'quiz_options_so':['propagate کردنی هەڵە','بەراوردکردن','ئۆپشنەل','سفر'],
 'quiz_options_ba':['Propagatekirina helayê','Berhevdankirin','Opsiyonel','Sifir'],'quiz_correct':0},
{'order':29,'level_so':s5so,'level_ba':s5ba,'title_so':'Concurrency - Threads','title_ba':'Concurrency - Threads',
 'content_so':'<p>Rust thread-safe یە. بە <code>std::thread::spawn</code> thread دروست دەکرێت:</p><pre>use std::thread;\nthread::spawn(|| { println!("Thread nû"); }).join().unwrap();</pre>',
 'content_ba':'<p>Rust thread-safe e. Bi <code>std::thread::spawn</code> thread tê çêkirin:</p>',
 'code':'use std::thread;\nuse std::sync::{Arc,Mutex};\nfn main() {\n    let kot = Arc::new(Mutex::new(0));\n    let mut handles = vec![];\n    for _ in 0..5 {\n        let k = Arc::clone(&kot);\n        handles.push(thread::spawn(move || {\n            let mut m = k.lock().unwrap();\n            *m += 1;\n        }));\n    }\n    for h in handles { h.join().unwrap(); }\n    println!("Kot: {}", *kot.lock().unwrap());\n}',
 'example_output':'Kot: 5',
 'quiz_type':'choice','quiz_question_so':'Arc<Mutex<T>> لە Rust بۆ چی بەکاردێت؟','quiz_question_ba':'Arc<Mutex<T>> di Rust de bO çi tê bikaranîn?',
 'quiz_options_so':['thread-safe هاوبەش کردنی داتا','خوێندنی فایل','دروستکردنی Struct','گۆڕینی نرخ'],
 'quiz_options_ba':['Thread-safe parvekirina danê','Xwendina file','Çêkirina struct','Guherandina nirxê'],'quiz_correct':0},
{'order':30,'level_so':s5so,'level_ba':s5ba,'title_so':'کۆتایی کۆرس — پرۆژەی کۆتایی','title_ba':'Dawiya Kursê — Proje ya Dawî',
 'content_so':'<p>ئافەرین! گەیشتیتە کۆتایی کۆرسی Rust. ئەوەی فێربوویت: let/mut، جۆرەکان، match، خولگەکان، Ownership، Borrowing، Struct، Enum، Option، Result، Trait، Generic، Closure، Iterator، HashMap، File I/O.</p>',
 'content_ba':'<p>Aferîn! Gihîştî dawiya kursê yê Rust. Fêrbûyî: let/mut، cureyan، match، gêrxistinên، Ownership، Struct، Enum، Option، Result، Trait، Generic، Closure، Iterator.</p>',
 'code':'use std::collections::HashMap;\nstruct Bank {\n    hejar: HashMap<String,f64>\n}\nimpl Bank {\n    fn new() -> Self { Bank{hejar:HashMap::new()} }\n    fn dagirtin(&mut self,nav:&str,miqdar:f64) { *self.hejar.entry(nav.to_string()).or_insert(0.0)+=miqdar; }\n    fn hesab(&self,nav:&str)->f64 { *self.hejar.get(nav).unwrap_or(&0.0) }\n}\nfn main() {\n    let mut b=Bank::new();\n    b.dagirtin("Azad",500.0);\n    b.dagirtin("Azad",250.0);\n    b.dagirtin("Baran",800.0);\n    println!("Azad: {}", b.hesab("Azad"));\n    println!("Baran: {}", b.hesab("Baran"));\n    println!("Ciya: {}", b.hesab("Ciya"));\n}',
 'example_output':'Azad: 750\nBaran: 800\nCiya: 0',
 'quiz_type':'practice',
 'practice_question_so':'بەرنامەیەک بنووسە کە لەگەڵ Struct و impl میتۆدێکی تەلاری چاپ بکات.',
 'practice_question_ba':'Bernameyeke binivîse ko ligel Struct û impl metodeke telara çap bike.',
 'expected_output_text':'Şêwe: Çargoşe, Rûber: 20','solution_code':'struct Çargoşe{d:f64,p:f64}\nimpl Çargoşe{fn ruber(&self)->f64{self.d*self.p}}\nfn main(){\n    let s=Çargoşe{d:4.0,p:5.0};\n    println!("Şêwe: Çargoşe, Rûber: {}",s.ruber());\n}','attempts_allowed':5},
# DONE_RUST
]
run('add_rust_v2.php','Rust','-OysGzfS5Qi08XHYs_FL',rust)
print('gen_rust.py complete')




